### ISSUE TITLE
Fail to connect to redis thru unix socket

### ISSUE THREAD

**Issue by marcos-guerrero** [phpredis/phpredis#1664] opened 2019-11-04 14:39 UTC
### Expected behaviour

I have a redis server listen on TCP 127.0.0.1:6379 and on a unix socket /var/run/redis/redis-server.sock
On My Ubuntu 18.04, PHP 7.3 and PHP Redis 5.0.2 I´m able to connect thru unixsocket using this code

```
<?php
$r = new Redis();
try {
        if ($r->connect("/var/run/redis/redis-server.sock")) {
                echo "Connected!";
        }

}
catch (Exception $e)
{
                echo "Exception: " . $e->getMessage() . "\n";
}

```

The output is "Connected!"

### Actual behaviour

On the same machine, I've installed PHP7.4RC and compiled PHP Redis 5.1.0:
./configure
make
sudo make install

 and the behaviour now is:

PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/ubuntu/redis.php on line 4
Exception: php_network_getaddresses: getaddrinfo failed: Name or service not known
 

If I use TCP: 
`$r->connect('127.0.0.1', 6379)` 
The connection works and I get "Connected!"

### I'm seeing this behaviour on
- OS: Ubuntu 18.04
- Redis: 4.0.9
- PHP: 7.4RC4
- phpredis: 5.1.0

I've compiled the phpredis-develop but the behaviour is the same

### I've checked
- [x ] There is no similar issue from other users
- [ x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment] 2019-11-04 14:53
@marcos-guerrero you should specify scheme `unix://`

**Comment by marcos-guerrero** [comment] 2019-11-04 14:59
Hi!
Thank you for your fast response, but how to do that?

I've tried :

$r->connect("unix:/var/run/redis/redis-server.sock") 
$r->connect("unix://var/run/redis/redis-server.sock") 
$r->connect("unix:///var/run/redis/redis-server.sock") 

without success

Anyway ... Where is it documented? On 5.0.2 it was working the way I wrote:
$r->connect("/var/run/redis/redis-server.sock")

**Comment by yatsukhnenko** [comment] 2019-11-04 15:02
Sorry, I answered without checking the code :smile: 
It seems that when port is not specified default value `-1` becomes `65535` and condition fails

**Comment by yatsukhnenko** [comment] 2019-11-04 15:08
Here is a patch that should fix this issue
```c
diff --git a/library.c b/library.c
index 8921c0f..98ec4ad 100644
--- a/library.c
+++ b/library.c
@@ -1753,7 +1753,7 @@ PHP_REDIS_API void redis_debug_response(INTERNAL_FUNCTION_PARAMETERS, RedisSock
  * redis_sock_create
  */
 PHP_REDIS_API RedisSock*
-redis_sock_create(char *host, int host_len, unsigned short port,
+redis_sock_create(char *host, int host_len, int port,
                   double timeout, double read_timeout,
                   int persistent, char *persistent_id,
                   long retry_interval)
diff --git a/library.h b/library.h
index 11da7a4..05ef917 100644
--- a/library.h
+++ b/library.h
@@ -48,7 +48,7 @@ PHP_REDIS_API void redis_info_response(INTERNAL_FUNCTION_PARAMETERS, RedisSock *
 PHP_REDIS_API void redis_parse_info_response(char *response, zval *z_ret);
 PHP_REDIS_API void redis_parse_client_list_response(char *response, zval *z_ret);
 PHP_REDIS_API void redis_type_response(INTERNAL_FUNCTION_PARAMETERS, RedisSock *redis_sock, zval *z_tab, void *ctx);
-PHP_REDIS_API RedisSock* redis_sock_create(char *host, int host_len, unsigned short port, double timeout, double read_timeout, int persistent, char *persistent_id, long retry_interval);
+PHP_REDIS_API RedisSock* redis_sock_create(char *host, int host_len, int port, double timeout, double read_timeout, int persistent, char *persistent_id, long retry_interval);
 PHP_REDIS_API int redis_sock_connect(RedisSock *redis_sock);
 PHP_REDIS_API int redis_sock_server_open(RedisSock *redis_sock);
 PHP_REDIS_API int redis_sock_auth(RedisSock *redis_sock);
```

**Comment by marcos-guerrero** [comment] 2019-11-04 15:12
Ok, thank you very much for your help! 

As I'm newbie with patches I'll keep using TCP connections until your patch goes into the code and the bug is fixed

**Comment by yatsukhnenko** [comment] 2019-11-04 15:14
You can also try to set port to `0`

**Comment by marcos-guerrero** [comment] 2019-11-04 15:17
My use of phpredis is behind phpfastcache, so I'm not able to tweak the connection params, once I configure 'path' param in phpfastcache, the 'port' value is not used...
Anyway, thanks again for your help

**Comment by yatsukhnenko** [comment] 2019-11-04 15:18
I think we will discuss this issue with @michael-grunder and create 5.1.1 soon

**Comment by michelecurletta** [comment] 2019-11-04 16:11
I've the same issue. Any timeline for the patch public release?

**Comment by dhazelett** [comment] 2019-11-04 21:10
Also affected. interesting that simply changing the signature broke it. setting to `0` also worked for us.

**Comment by michelecurletta** [comment] 2019-11-04 22:41
> oke it. setting to `0` also worked for us.

unfortunately not for me :(

**Comment by michael-grunder** [comment] 2019-11-05 01:23
If people could confirm this is now fixed in the develop branch that would be great.

I added some tests so this regression shouldn't happen in the future.

**Comment by dhazelett** [comment] 2019-11-05 02:27
I'll see if I can test it tomorrow, might take me a minute to update one of the PQA AMIs tho lol

**Comment by yatsukhnenko** [comment] 2019-11-06 07:33
@dhazelett Were you able to test the change?

**Comment by dhazelett** [comment] 2019-11-08 17:51
Sorry, unfortunately it looks like our AMIs are too locked down to allow me to switch.

**Comment by yatsukhnenko** [comment] 2019-11-08 18:28
No worries, since we have unit tests for this it probably works.

**Comment by yatsukhnenko** [comment] 2019-11-11 07:45
5.1.1 released

**Closed by yatsukhnenko** 2019-11-11 07:45 UTC

**Comment by marcos-guerrero** [comment] 2019-11-11 08:04
5.1.1 already compiled and working as expected 
Thank you very much!

**Comment by dhazelett** [comment] 2019-11-11 09:43
I'll confirm in a few hours when we rebuild our AMIs for the week, thanks @yatsukhnenko

**Comment by victory7** [comment] 2020-10-07 16:04
I have the same issue with PHP 7.4.11 and phpredis 5.3.1
TCP connection works well but socket connection returns "no such file or directory" error exception.
I tried many types of paths like with or without port number or with "unix://" or not and no luck.

**Comment by yatsukhnenko** [comment] 2020-10-07 16:34
@victory7 did you specify relative path?
`unix:///run/redis.sock` works for me

**Comment by victory7** [comment] 2020-10-07 17:20
Yes I tried both relative and full paths.
/tmp/redis.sock
unix:///tmp/redis.sock
unix:/tmp/redis.sock

None of them didn't work for me!

**Comment by yatsukhnenko** [comment] 2020-10-08 17:25
@victory7 https://github.com/phpredis/phpredis/issues/1836

**Comment by victory7** [comment] 2020-10-15 09:41
My problem solved.
The issue was the different (unique) tmp directories for each service. Described here: 
https://serverfault.com/questions/463993/nginx-unix-domain-socket-error/464025#464025

So easily I changed "unixsocket" value to "/var/run/redis/redis.sock" and now PHP can find socket file and connection established successfully.

**Comment by RoodFruit** [comment] 2021-08-23 14:39
> You can also try to set port to `0`

Thank you so much. This fixed it for me in Lumen.
