### ISSUE TITLE
2.2.8 memory allocation issue / SIGSEGV

### ISSUE THREAD

**Issue by pnu** [phpredis/phpredis#852] opened 2016-06-28 14:16 UTC
Some of our php apps started to fail few days again, when deploying to new production environment with phpredis 2.2.8. The error is something like this: `PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 140082498947888 bytes) in Unknown on line 0`. The php-fpm processes die to SIGSEGV. Downgrading to 2.2.7 fixed the issue.

This is on Heroku (cedar-14) stack, deployed with the heroku-buildpack-php. The issue is easy to reproduce by changing the required `ext-redis` version in the composer.json. I've also reported this to the Heroku team.

**Comment by dzuelke** [comment] 2016-06-28 14:29
Do you have a reproduce script that triggers that error, @pnu? Are you using clustering like in #845?

**Comment by pnu** [comment] 2016-06-28 14:56
I don't have a script, and unfortunately this happens only for some of the apps. The exact mechanism is unknown to me, except it's consistently avoided and triggered again, by changing the ext-redis version, and only that. I know this makes the issue a bit non-actionable, so I'll have to dig deeper, or "hope" someone else may find a similar issue, in a more actionable setting.

Actually, we're not using clustering, so I can't really say if this is related or not; I'll remove the reference from original comment.

**Comment by michael-grunder** [comment] 2016-07-01 00:16
This is most likely an overflow error (trying to allocate a negative unsigned amount of memory).  It's hard to say without a specific script that can cause it however.

**Comment by dzuelke** [comment] 2016-07-05 12:26
@pnu do you think you could try and narrow this down a little please? Does this happen on a dev Ubuntu setup as well?

**Comment by dzuelke** [comment] 2016-07-05 12:26
#853 might be related, @michael-grunder

**Comment by dzuelke** [comment] 2016-07-05 12:28
Or if you can't reproduce it locally, but at least have a reliable-ish way of triggering it on a Heroku dev/staging/test app, @pnu, I could try and create a special `ext-redis` build for you with the fixes from #862, would you be willing to work with me on that?

**Comment by yatsukhnenko** [comment] 2017-04-05 13:37
Probably it was fixed in 3.1.2.

**Closed by yatsukhnenko** 2017-04-05 13:37 UTC
