### ISSUE TITLE
SETS stored as intset, avoid hashtable

### ISSUE THREAD

**Issue by steamboatid** [phpredis/phpredis#2001] opened 2021-08-23 13:17 UTC
### Expected behaviour
KeyDB (or maybe REDIS) store SETS as **intset** if inputed with **integer** values.
If possible, please add dedicated method to phpredis, named as _sAddInt_ and _sAddIntArray_ to utilize **intset**

FYI, I store about 50K items in SETS.
I believe it will reduce the memory needed, if we can utilize intset SETS at Redis or KeyDB

### Actual behaviour
KeyDB always save SETS as hashtable.

### I'm seeing this behaviour on
- OS: Debian 10
- Redis: keydb 5.1.1
- PHP: 8.0.9
- phpredis: 

### Steps to reproduce, backtrace or example script
$serializer = array(
	'igbinary' => Redis::SERIALIZER_IGBINARY,
	'php' => Redis::SERIALIZER_PHP,
	'none' => Redis::SERIALIZER_NONE,
);

foreach ($serializer as $ser_idx => $ser_val) {
	$tkey = 'tkey' . $ser_idx . time();
	$redis->setOption(Redis::OPT_SERIALIZER, $ser_val);
	$redis->sAddArray($tkey, range(1, 10));
	$arr = $redis->sMembers($tkey);
	$enc = $redis->object('encoding', $tkey);
	printf("Serializer=%9s, Encoding= %s \n", $ser_idx, $enc);
}

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment] 2021-08-25 19:02
This isn't under phpredis' control.

There is a `redis-server` configuration value called `set-max-intset-entries` which determines how large sets can be before they are converted into a hash table.

This program illustrates that:

```php
<?php

function printSetInfo($redis, $key) {
    echo "'$key' cardinality: " . $redis->sCard('myset') . ', encoding: ' . $redis->object('encoding', 'myset') . "\n";
}

$redis = new Redis;
$redis->connect('localhost', 6379);

$max = $redis->config('get', 'set-max-intset-entries');
$max = $max['set-max-intset-entries'];

echo "Max intset values: $max\n";

$redis->del('myset');
for ($i = 0; $i < $max; $i++) {
    $redis->sAdd('myset', $i);
}

// Set has <= set-max-intset-entries, Will be encoded as an 'intset'
printSetInfo($redis, 'myset');

// Adding another item causes Redis to convert the set to a 'hashtable'
$redis->sAdd('myset', $i);
printSetInfo($redis, 'myset');
```

You can likely increase that setting much higher than `512` but you will need to test whether it works in your use-case.  The `intset` encoding is much more memory efficient but has `O(N)` insert performance which could present a problem when the sets get much larger.

**Comment by michael-grunder** [comment] 2021-08-25 21:53
Closing this, since it's not a bug in PhpRedis (or even under our control) but feel free to ask any other questions you have.

**Closed as completed by michael-grunder** 2021-08-25 21:53 UTC

**Comment by steamboatid** [comment] 2021-08-26 07:17
thank you for the kind response.

I've tried to increase `set-max-intset-entries` to a very large number (10K in my case), but at production. KeyDB still convert to "hastable" encodings.

so what about adding **sAddInt** and **sAddIntArray** just to make sure that we send integer/long to the server ?

it seem that we need to add `redis_key_long_arr_cmd` as addition to existing `redis_key_str_arr_cmd` and `redis_key_val_arr_cmd`

**Comment by michael-grunder** [comment] 2021-08-26 19:38
I don't see this behavior.

If I start an instance of KeyDB like so:
```bash
❯ src/keydb-server --port 10000 --save "" --set-max-intset-entries 10000
```

And then run my little test script, I get the output I would expect (`intset` until the set has more than 10000 elements):

```bash
❯ php /tmp/intset.php
Max intset values: 10000
'myset' cardinality: 10000, encoding: intset
'myset' cardinality: 10001, encoding: hashtable
```

Also, KeyDB [just tests if the input string can be converted to a long](https://github.com/EQ-Alpha/KeyDB/blob/0be40b9fd43ec4e7802e09fa627ad91b2e387707/src/t_set.cpp#L63)

You may be running into an issue where a set is _already_ a `HashTable` since KeyDB and Redis don't convert them back AFAIK.
