### ISSUE TITLE
geodist (and probably other geo methods) not found (2.2.8-devphp7)

### ISSUE THREAD

**Issue by logless** [phpredis/phpredis#1061] opened 2016-12-16 12:57 UTC
When installing php-redis via apt-get on Ubuntu 16 (php 7.0 fpm), the geo functions are not available. The version that gets installed is 2.2.8-devphp7. 

When compiled from source, there is strange behaviour with arrays (for instance hGetAll is not returning an associative array, but a raw array). 

Is there a way to enforce installing the latest version via apt-get?

**Comment by remicollet** [comment] 2016-12-16 16:12
I think this is rather a downstream (distro) bug ;)  You should probably ask your deb provider.

**Comment by michael-grunder** [comment] 2016-12-19 20:03
Closing this.  Feel free to reopen if the issue is here.

**Closed by michael-grunder** 2016-12-19 20:03 UTC
