### ISSUE TITLE
TLS Connection is freezing

### ISSUE THREAD

**Issue by srbt** [phpredis/phpredis#2440] opened 2024-02-05 16:16 UTC
### Expected behaviour
Code:
```
php -r '$redis = new Redis(); $redis->connect("tls://cache-test", 6379); echo serialize($redis->keys("*"));'
```
returns:
```
'a:0:{}'
```
### Actual behaviour
In 1 of 6 case this freezes for more then 10s. (This is timeout used in test, really this freezes for hours... until I kill this).

### I'm seeing this behaviour on
- OS: Dockerized debian **11.8**
- Redis: docker image redis:**7.0.7**
- PHP: docker image php:**8.0.30**-apache, tested with php:**8.1**-apache and php:**8.3**-apache with same result
- phpredis: pecl **6.0.2**

Without TLS working all every time good.

### Steps to reproduce, backtrace or example script
[Bats](https://github.com/bats-core/bats-core) test that:
- creates a certification authority and a certificate,
- starts a redis instance with a certificate
- starts a php container with phpredis
- installs a certification authority into it
- contacts redis through socket (with output verification) (always succeed)
- contacts redis through phpredis (with output validation) (sometimes fail)
- terminates used containers

```
#!/usr/bin/env bats
4
load bats-helpers/bats-support/load
load bats-helpers/bats-assert/load
load bats-extensions/docker/load

setup() {
  export REDIS_VERSION=7.0.7
  export TEST_CONTEXT="${USER}_$$_${RANDOM}"
  export TEST_NETWORK="${TEST_CONTEXT}"
  export IMAGE_PHPS="php:8.0.30-apache"
  mkdir "${TEST_CONTEXT}"
  docker network create "${TEST_NETWORK}"
}

@test "redis" {
  mkdir "${TEST_CONTEXT}/certs"
  docker run -u "${UID}" -v "${PWD}/functions:/functions" -v "${PWD}/${TEST_CONTEXT}/certs:/certs" --rm -i --entrypoint bash "${IMAGE_PHPS}" /functions/createCa.sh /certs
  docker run -u "${UID}" -v "${PWD}/functions:/functions" -v "${PWD}/${TEST_CONTEXT}/certs:/certs" --rm -i --entrypoint bash "${IMAGE_PHPS}" /functions/createCert.sh /certs cache-test
  docker build --build-arg IMAGE_PHPS -t "${TEST_CONTEXT}_php" -t test_php php-server
  chmod 644 "${TEST_CONTEXT}/certs/"*
  docker run -d -v "${PWD}/${TEST_CONTEXT}/certs:/certs" --network "${TEST_NETWORK}" --hostname "cache-test" --name "${TEST_CONTEXT}_cache" "redis:${REDIS_VERSION:?}" --tls-port 6379 --port 0 --tls-cert-file /certs/site.test.crt --tls-key-file /certs/site.test.key --tls-ca-cert-file /certs/myCA.pem --tls-auth-clients no --loglevel debug
  wait_for_container_log "${TEST_CONTEXT}_cache" "Ready to accept connections"
  run docker run -d -v "${PWD}/functions:/functions" -v "${PWD}/${TEST_CONTEXT}/certs:/certs" --network "${TEST_NETWORK}" --hostname "php" --name "${TEST_CONTEXT}_php" "${TEST_CONTEXT}_php"
  assert_success
  run docker exec -u 'root:root' -i "${TEST_CONTEXT}_php" bash /functions/installCa.sh /certs
  assert_success
  assert_output --partial '1 added, 0 removed; done.'
  printf 'php -i\n'
  run docker exec "${TEST_CONTEXT}_php" php -i
  assert_success
  assert_output --partial 'redis'
  printf 'stream_socket_client(); fwrite(ping)\n'
  run timeout -v 10s docker exec "${TEST_CONTEXT}_php" php -r '$con = stream_socket_client("tls://cache-test:6379", $error, $errors,STREAM_CLIENT_CONNECT); fwrite($con, "PING\n"); echo fgets($con); fclose($con);'
  assert_success
  assert_output $'+PONG\r'
  printf 'stream_socket_client(); fwrite(keys)\n'
  run timeout -v 10s docker exec "${TEST_CONTEXT}_php" php -r '$con = stream_socket_client("tls://cache-test:6379", $error, $errors,STREAM_CLIENT_CONNECT); fwrite($con, "KEYS *\n"); echo fgets($con); fclose($con);'
  assert_success
  assert_output $'*0\r'
  printf 'Redis()->ping()\n'
  run timeout -v 10s docker exec "${TEST_CONTEXT}_php" php -r '$redis = new Redis(); $redis->connect("tls://cache-test", 6379); echo $redis->ping("PONG");'
  assert_success
  assert_output --partial 'PONG'
  printf 'Redis()->keys()\n'
  run timeout -v 10s docker exec "${TEST_CONTEXT}_php" php -r '$redis = new Redis(); $redis->connect("tls://cache-test", 6379); echo serialize($redis->keys("*"));'
  assert_success
  assert_output --partial 'a:0:{}'
}

teardown() {
  docker rm -f "${TEST_CONTEXT}_cache" "${TEST_CONTEXT}_php"
  docker rmi "${TEST_CONTEXT}_php"
  docker network rm "${TEST_NETWORK}"
  rm -rf "${TEST_CONTEXT}"
}
```
Typical failure output is:
```
$ ./test.sh
redis.bats
 ✗ redis
   (from function `assert_success' in file bats-helpers/bats-assert/src/assert_success.bash, line 42,
    in test file redis.bats, line 47)
     `assert_success' failed
   2685667e06a807672c0291f6c37fd6010e606efc403651016fd7c5fbec5ad083
   Generating RSA private key, 2048 bit long modulus (2 primes)
   .........+++++
   ....................................................+++++
   e is 65537 (0x010001)
   Generating RSA private key, 2048 bit long modulus (2 primes)
   .............................................................+++++
   ................................................................................................................+++++
   e is 65537 (0x010001)
   Signature ok
   subject=C = CZ, ST = Czech Republic, L = Prague, O = CEE-Systems, OU = IT, CN = TestsSite, emailAddress = tomas.srb@travelportgds.cz
   Getting CA Private Key
   Sending build context to Docker daemon  2.048kB
   Step 1/3 : ARG IMAGE_PHPS
   Step 2/3 : FROM "${IMAGE_PHPS}"
    ---> 3357132d6ece
   Step 3/3 : RUN pecl install redis-6.0.2 && docker-php-ext-enable redis
    ---> Using cache
    ---> 7d646225d937
   Successfully built 7d646225d937
   Successfully tagged srb_1141315_29856_php:latest
   Successfully tagged test_php:latest
   4373a8763ae7554ae4afef2ce5cee8c2edfaf7fe9ec9777cb0659cc6690d9a0c
   Waiting for "Ready to accept connections" in "srb_1141315_29856_cache"  done.
   php -i
   stream_socket_client(); fwrite(ping)
   stream_socket_client(); fwrite(keys)
   Redis()->ping()
   Redis()->keys()
   
   -- command failed --
   status : 124
   output : timeout: sending signal TERM to command 'docker'
   --
   
   srb_1141315_29856_cache
   srb_1141315_29856_php
   Untagged: srb_1141315_29856_php:latest
   srb_1141315_29856

1 test, 1 failure
```

Dockerfile for php-server contains for caching of phpredis installation:
```
ARG IMAGE_PHPS
FROM "${IMAGE_PHPS}"

RUN pecl install redis-6.0.2 && docker-php-ext-enable redis
```
Here are all used files (dependencies are `bash`, `git` and `docker`): 
[tests-redis.tar.gz](https://github.com/phpredis/phpredis/files/14168210/tests-redis.tar.gz)

Here is improved version with loop for easiest use (dependencies are `bash`, `git` and `docker`):
[tests-redis.tar.gz](https://github.com/phpredis/phpredis/files/14176951/tests-redis.tar.gz)
```
$ ./test.sh --stats
Try no 1
redis.bats
 ✓ redis

1 test, 0 failures

Try no 2
redis.bats
 ✓ redis

1 test, 0 failures

Try no 3
redis.bats
 ✗ redis
...
Try no 30
redis.bats
 ✓ redis

1 test, 0 failures


12 errors in 30 runs
[..!..!!!..!.!.!......!!..!!.!.]
```
### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment] 2024-02-11 09:15
I guess the problem is similar to discussed in https://github.com/phpredis/phpredis/issues/1726 so closing this issue

**Closed as completed by yatsukhnenko** 2024-02-11 09:15 UTC
