### ISSUE TITLE
Persistent Connection Corruption

### ISSUE THREAD

**Issue by iliaal** [phpredis/phpredis#1655] opened 2019-10-21 13:20 UTC
### Expected behaviour

No Errors

### Actual behaviour
Variety of errors indicating that connection handle is not "clean", errors are like this:

PHP Fatal error: Uncaught Exception: protocol error, got ']' as reply type byte
Response returning +PONG as opposed to data

### I'm seeing this behaviour on
- OS: Ubuntu 18.04
- Redis: 5.0.4
- PHP: 7.2.23
- phpredis: 5.0.2

I've attempted to turn of connection pooling, that made errors slightly less frequent, but they still happen.

**Comment by marcdejonge** [comment] 2019-10-29 09:01
Yes, we see the same problems again with 5.0.2. When a connection is corrupted, the reconnect doesn't clean the connection completely. We've completely disabled persistent connections for now as a work-around.

**Comment by yatsukhnenko** [comment] 2019-10-31 17:09
@iliaal @marcdejonge could you test following patch?
```c
diff --git a/library.c b/library.c
index 8921c0f..4bbc9e2 100644
--- a/library.c
+++ b/library.c
@@ -1953,7 +1953,7 @@ redis_sock_disconnect(RedisSock *redis_sock, int force)
             if (INI_INT("redis.pconnect.pooling_enabled")) {
                 p = redis_sock_get_connection_pool(redis_sock);
             }
-            if (force) {
+            if (force || !IS_ATOMIC(redis_sock)) {
                 php_stream_pclose(redis_sock->stream);
                 if (p) p->nb_active--;
             } else if (p) {
```

**Comment by iliaal** [comment] 2019-11-06 16:47
@yatsukhnenko That looks like it would fix the connection termination, but not the underlying corruption?

**Comment by yatsukhnenko** [comment] 2019-11-06 17:18
@iliaal I think that corruption is caused by non-properly terminated connection

**Comment by iliaal** [comment] 2019-11-10 16:23
@yatsukhnenko I tried the updated code locally, I can't seem to reproduce the issue anymore.

**Comment by yatsukhnenko** [comment] 2019-11-10 16:36
@iliaal we created [another issue](https://github.com/phpredis/phpredis/issues/1668) we will try to find right solution for this issue.

**Comment by yatsukhnenko** [comment] 2019-11-23 14:02
@iliaal could you test changes from `issue.1668` branch?

**Comment by michael-grunder** [comment] 2019-12-04 17:38
Closing this in favor of #1668

**Closed by michael-grunder** 2019-12-04 17:38 UTC
