### ISSUE TITLE
debug read error on connection

### ISSUE THREAD

**Issue by sorinv** [phpredis/phpredis#70] opened 2011-10-30 19:14 UTC
Hi there,

I am getting a lot of "read error on connection" errors. Server is under load, but not a lot. I traced this to always happen here:
- library.c
- redis_sock_read
- php_stream_gets -> this returns NULL, so it triggers the exception.

Any way I can further debug this to figure out why it happens?

Thanks,
Sorin

**Comment by bmeynell** [comment] 2015-03-26 17:30
Also encountering this error quite often on a single node setup with the client on the same node.

**Comment by parhamr** [comment] 2015-03-26 17:42
@bmeynell are you using TCP or Unix sockets? (e.g. does your config have `bind 127.0.0.1` or `unixsocket /tmp/redis.sock`?)

**Comment by bmeynell** [comment] 2015-03-26 18:25
@parhamr - Both are commented out in the redis config file. So I *think* that's equivalent to `bind 0.0.0.0`.

**Comment by andygrunwald** [comment] 2015-03-29 14:54
@bmeynell my experience about this error is: Timeouts / Long running operations on Redis.
We had this error and we had stripped it down.
Please have a look what operations you fire up on the redis node. `keys *`? O(n) operations where n is big? A useful tool about this is [Watchdog](http://redis.io/topics/latency). It is like the "MySQL slow query log for redis".

The next thing is: How you connect to Redis? Do you open a new connection on every request? Or do you use a proxy like [twemproxy](https://github.com/twitter/twemproxy)?
We encountered during high load (>2.500 req/s) that twemproxy solved a lot of this connection issues. Before this we say "Hi", fire up one cmd, and say "bye" to redis more than >2.500 times per second.
It seems that redis was "quite busy" with connection handling instead of doing cmd works :)

**Comment by rahulpatil323** [comment] 2015-07-23 23:05
I see the thread is not active anymore but was anything done in phpredis to fix this?

**Comment by virgofx** [comment] 2015-10-27 17:54
This can still easily be duplicated in PHP by creating a connection to Redis and then writing keys in a loop over more than one fork. (Happens in as few as 10 writes in a for loop).

**Comment by parhamr** [comment] 2015-10-27 17:56
@virgofx would you please provide your sample code in here? That would be helpful to reproduce and fix the bug (by whomever finally takes it on).

**Comment by virgofx** [comment] 2015-10-27 18:49
@parhamr Hopefully this script can provide insight into the issue. I've adapted it from our core enterprise usage into a small little test runner.

**Usage**

1) Update the following constants:
* `host`
* `password`
* `fork`
* `iterationsPerFork`
Note:  You need at least 2 forks and about 10 iterations to begin seeing errors.

2) Run via `php redis-test.php`

**redis-test.php**
```php
<?php

/**
 * Utility class to easily fork processes (Adapted for phpredis/phpredis - Issue #70)
 */
class Forker
{
    private $childProcesses = [];

    public function fork($callback, $supressSocketErrors = false)
    {
        $sockets = stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP);
        $pid = pcntl_fork();

        if ($pid == -1) {
            throw new \Exception('Could not fork process');
        } elseif ($pid) {
            fclose($sockets[1]);
            $this->childProcesses[] = [
                'pid'    => $pid,
                'socket' => $sockets[0]
            ];
        } else {
            // If there was no pid and no error, then this is the child process
            fclose($sockets[0]);
            $return = $callback();

            if ($supressSocketErrors) {
                set_error_handler(function ($error_handler, $error_types) {});
            }
            if (fwrite($sockets[1], serialize($return))) {
                fclose($sockets[1]);
            }
            if ($supressSocketErrors) {
                restore_error_handler();
            }

            // Exit the child process cleanly
            exit(0);
        }

        return $pid;
    }

    public function wait($callback = false)
    {
        foreach ($this->childProcesses as $index => $childProcess) {
            pcntl_waitpid($childProcess['pid'], $status, WUNTRACED);

            // See if the process exited clean, or if there was an error
            if ($status > 0) {
                throw new \Exception('Child process exited unclean');
            }

            if ($callback !== false) {
                $return = stream_get_contents($childProcess['socket']);
                $callback(unserialize($return));
            }

            unset($this->childProcesses[$index]);
        }
    }

}

//////////////////////////////////////////////////////////////////////////////////////////////
// PHP CLI Runner
//////////////////////////////////////////////////////////////////////////////////////////////
$host = '127.0.0.1';
$port = 6379;
$password = 'your password';
$forks = 2;
$iterationsPerFork = 10;


$redis = new \Redis();
$redis->connect($host, $port);

if ($redis->auth($password) === false) {
    throw new \Exception('Redis authentication failed');
}

// Spin up forks and spam data
$forker = new \Forker();

for ($i = 0; $i < $forks; $i++) {
    $forker->fork(function() use ($iterationsPerFork, $forks, $i, $redis) {
        for ($idx = 0; $idx < $iterationsPerFork; $idx++) {
            try {

                if (! $redis->setex('S:' . md5(uniqid($i . $idx, true)), 1440, 'small-data')) {
                    echo '[fork ' . $i . '] [' . $idx . '] Unable to setex()' . PHP_EOL;
                } else {
                    echo '[fork ' . $i . '] [' . $idx . '] ✓' . PHP_EOL;
                }
            } catch (Exception $e) {
                echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . PHP_EOL;
            }
        }
    });
}
$forker->wait();
```

`redis-test.php` (2 x 10)  (Bugs out, see errors)
```
[fork 0] [0] ✓
[fork 1] [0] ✓
[fork 1] [1] ✓
[fork 0] [1] read error on connection
[fork 1] [2] ✓
[fork 1] [3] ✓
[fork 0] [2] Unable to setex()
[fork 0] [3] Unable to setex()
[fork 0] [4] Unable to setex()
[fork 0] [5] Unable to setex()
[fork 0] [6] Unable to setex()
[fork 0] [7] Unable to setex()
[fork 0] [8] Unable to setex()
[fork 1] [4] ✓
[fork 0] [9] Unable to setex()
[fork 1] [5] ✓
[fork 1] [6] ✓
[fork 1] [7] ✓
[fork 1] [8] ✓
[fork 1] [9] ✓
```

Re-test with just one fork - Works, no issues.
`redis-test.php` (1 x 10000)
```
[fork 0] [0] ✓
....
[fork 0] [9999] ✓
```

**Comment by wotek** [comment] 2015-11-03 16:24
+1 on the issue

**Comment by jianhuihi** [comment] 2015-11-10 10:03
+1 on the issue

**Comment by mightydok** [comment] 2015-11-19 12:56
@virgofx @michael-grunder test script works whell with php**i**redis.
For phpredis even patch for php-src from @shafreeck dont help.

**Comment by virgofx** [comment] 2015-11-20 14:25
Bummer, would be great if we could get a fix for this :disappointed:

**Comment by mightydok** [comment] 2015-11-22 17:01
@virgofx as is see phpredis need rewrite network code, cause hiredis (c library for phpiredis) looks more mature and more well orginized code structure.

**Comment by virgofx** [comment] 2015-11-30 02:59
@mightydok I'm just concerned about getting the phpredis package updated as this is the most widely used PHP extension for Redis. If there is a suitable replacement the community would certainly move that direction ... but right now phpredis is the defacto standard.

**Comment by michael-grunder** [comment] 2015-11-30 07:47
I don't know what is causing this to happen in the context of a fork, but
I'll try to figure it out with your script.

I am updating phpredis and fixing bugs but we do need a new official
package that includes cluster support.  Truth is I'm finishing up a huge
project for my "real" job so I should have more time for this now.

Also I totally agree phpredis should use hiredis for its communication
layer, but that is a big task.

Cheers,
Mike

**Comment by virgofx** [comment] 2015-11-30 14:56
@michael-grunder Thanks. A network layer switch would be a big task and could definitely be scheduled for sometime in the future. Since we have a reproducible script for this long outstanding bug I figured it would be easier to trace down the issue to at least make a temporary fix.

**Comment by virgofx** [comment] 2016-01-12 01:05
@michael-grunder Figured you've been busy .. just wondering if you or anyone else has been able to make any progress on this issue?

**Comment by virgofx** [comment] 2016-01-18 16:47
@michael-grunder ?

**Comment by fucongcong** [comment] 2016-01-19 02:00
pconnect and connect both throw the exception

**Comment by eeroniemi** [comment] 2016-04-27 12:21
This is happening to us also on production (with latest stable driver version 2.2.7) and I was able to reproduce the issue with @virgofx's fork script, with both 2.2.7 and current phpredis devel branch build. 

Also I tried to make shot in the dark and see if I could somehow work my way around the issue by catching the exception and doing ping or by creating new Redis object + reconnecting + calling setex again when this error happens, but seems like that didn't help either. 

Here are my insights to save time from someone who is thinking the same (modified @virgofx's script):

```php
<?php

/**
 * Utility class to easily fork processes (Adapted for phpredis/phpredis - Issue #70)
 */
class Forker
{
	private $childProcesses = [];

	public function fork($callback)
	{
		$sockets = stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP);
		$pid = pcntl_fork();

		if ($pid === -1) {
			throw new \Exception('Could not fork process');
		} elseif ($pid) {
			fclose($sockets[1]);
			$this->childProcesses[] = [
				'pid'    => $pid,
				'socket' => $sockets[0]
			];
		} else {
			fclose($sockets[0]);
			$return = $callback();

			if (fwrite($sockets[1], serialize($return))) {
				fclose($sockets[1]);
			}

			exit(0);
		}

		return $pid;
	}

	public function wait()
	{
		foreach ($this->childProcesses as $index => $childProcess) {
			pcntl_waitpid($childProcess['pid'], $status, WUNTRACED);

			if ($status > 0) {
				throw new \Exception('Child process exited unclean');
			}

			unset($this->childProcesses[$index]);
		}
	}

}

//////////////////////////////////////////////////////////////////////////////////////////////
// PHP CLI Runner
//////////////////////////////////////////////////////////////////////////////////////////////
$host = '127.0.0.1';
$port = 6379;
$forks = 3;
$iterationsPerFork = 10;
$timeout = 2;

$redis = new \Redis();
$redis->connect($host, $port, $timeout);

$forker = new \Forker();

function setRedisData($redis, $key, $data, $i, $idx) {
	if (! $redis->setex($key, 1440, $data)) {
		echo '[fork ' . $i . '] [' . $idx . '] Unable to setex()' . PHP_EOL;
	} else {
		echo '[fork ' . $i . '] [' . $idx . '] ✓' . PHP_EOL;
	}

}

for ($i = 0; $i < $forks; $i++) {
	$forker->fork(function() use ($iterationsPerFork, $forks, $i, $redis) {
		for ($idx = 0; $idx < $iterationsPerFork; $idx++) {
			$key = 'S:' . md5(uniqid($i . $idx, true));
			$data = 'small-data';
			try {
				setRedisData($redis, $key, $data, $i, $idx);
			} catch (\Exception $e) {
				echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - trying to reconnect and set data again' . PHP_EOL;
				if ($e->getMessage() == 'read error on connection"') {
					// $redis->ping(); // doesn't help
					// reconnecting doesn't help either
					unset($redis);
					$redis = new \Redis();
					$redis->connect($host, $port, $timeout);
					setRedisData($redis, $key, $data, $i, $idx);
				}
			}
		}
	});
}
$forker->wait();
```

Output:

```
[fork 0] [0] ✓
[fork 0] [1] ✓
[fork 0] [2] ✓
[fork 0] [3] ✓
[fork 0] [4] ✓
[fork 0] [5] ✓
[fork 0] [6] ✓
[fork 0] [7] ✓
[fork 0] [8] ✓
[fork 0] [9] ✓
[fork 1] [0] read error on connection - trying to reconnect and set data again
[fork 1] [1] Unable to setex()
[fork 1] [2] Unable to setex()
[fork 1] [3] Unable to setex()
[fork 1] [4] Unable to setex()
[fork 1] [5] Unable to setex()
[fork 1] [6] Unable to setex()
[fork 1] [7] Unable to setex()
[fork 1] [8] Unable to setex()
[fork 1] [9] Unable to setex()
[fork 2] [0] ✓
[fork 2] [1] ✓
[fork 2] [2] ✓
[fork 2] [3] ✓
[fork 2] [4] ✓
[fork 2] [5] ✓
[fork 2] [6] ✓
[fork 2] [7] ✓
[fork 2] [8] ✓
[fork 2] [9] ✓
```

**Comment by eeroniemi** [comment] 2016-04-27 13:03
Here is the script where I tried to do workaround of reconnecting & calling setex again after connection failure, but it didn't work. Here is the modified script:

```
<?php

/**
 * Utility class to easily fork processes (Adapted for phpredis/phpredis - Issue #70)
 */
class Forker
{
	private $childProcesses = [];

	public function fork($callback)
	{
		$sockets = stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP);
		$pid = pcntl_fork();

		if ($pid === -1) {
			throw new \Exception('Could not fork process');
		} elseif ($pid) {
			fclose($sockets[1]);
			$this->childProcesses[] = [
				'pid'    => $pid,
				'socket' => $sockets[0]
			];
		} else {
			fclose($sockets[0]);
			$return = $callback();

			if (fwrite($sockets[1], serialize($return))) {
				fclose($sockets[1]);
			}

			exit(0);
		}

		return $pid;
	}

	public function wait()
	{
		foreach ($this->childProcesses as $index => $childProcess) {
			pcntl_waitpid($childProcess['pid'], $status, WUNTRACED);

			if ($status > 0) {
				throw new \Exception('Child process exited unclean');
			}

			unset($this->childProcesses[$index]);
		}
	}

}

//////////////////////////////////////////////////////////////////////////////////////////////
// PHP CLI Runner
//////////////////////////////////////////////////////////////////////////////////////////////
$host = '127.0.0.1';
$port = 6379;
$forks = 3;
$iterationsPerFork = 10;
$timeout = 2;

$redis = new \Redis();
$redis->connect($host, $port, $timeout);

$forker = new \Forker();

function setRedisData($redis, $key, $data, $i, $idx) {
	if (! $redis->setex($key, 1440, $data)) {
		echo '[fork ' . $i . '] [' . $idx . '] Unable to setex()' . PHP_EOL;
	} else {
		echo '[fork ' . $i . '] [' . $idx . '] ✓' . PHP_EOL;
	}

}

for ($i = 0; $i < $forks; $i++) {
	$forker->fork(function() use ($iterationsPerFork, $forks, $i, $redis) {
		for ($idx = 0; $idx < $iterationsPerFork; $idx++) {
			$key = 'S:' . md5(uniqid($i . $idx, true));
			$data = 'small-data';
			try {
				setRedisData($redis, $key, $data, $i, $idx);
			} catch (\Exception $e) {
				echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - trying to reconnect and set data again' . PHP_EOL;

				try {
					unset($redis);
					$redis = new \Redis();
					$redis->connect($host, $port, $timeout);
				} catch (\Exception $e) {
					echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - reconnection attempt failed' . PHP_EOL;
				}

				try {
					setRedisData($redis, $key, $data, $i, $idx);
				} catch (\Exception $e) {
					echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - reconnection ok, setting data failed' . PHP_EOL;
				}
			}
		}
	});
}
$forker->wait();
```

And output:

```
[fork 0] [0] ✓
[fork 0] [1] ✓
[fork 0] [2] ✓
[fork 0] [3] ✓
[fork 0] [4] ✓
[fork 0] [5] ✓
[fork 0] [6] ✓
[fork 0] [7] ✓
[fork 0] [8] ✓
[fork 0] [9] ✓
[fork 1] [0] ✓
[fork 1] [1] ✓
[fork 1] [2] ✓
[fork 1] [3] ✓
[fork 1] [4] ✓
[fork 1] [5] ✓
[fork 1] [6] ✓
[fork 1] [7] ✓
[fork 1] [8] ✓
[fork 1] [9] ✓
[fork 2] [0] read error on connection - trying to reconnect and set data again
[fork 2] [0] Redis server went away - reconnection ok, setting data failed
[fork 2] [1] Redis server went away - trying to reconnect and set data again
[fork 2] [1] Redis server went away - reconnection ok, setting data failed
[fork 2] [2] Redis server went away - trying to reconnect and set data again
[fork 2] [2] Redis server went away - reconnection ok, setting data failed
[fork 2] [3] Redis server went away - trying to reconnect and set data again
[fork 2] [3] Redis server went away - reconnection ok, setting data failed
[fork 2] [4] Redis server went away - trying to reconnect and set data again
[fork 2] [4] Redis server went away - reconnection ok, setting data failed
[fork 2] [5] Redis server went away - trying to reconnect and set data again
[fork 2] [5] Redis server went away - reconnection ok, setting data failed
[fork 2] [6] Redis server went away - trying to reconnect and set data again
[fork 2] [6] Redis server went away - reconnection ok, setting data failed
[fork 2] [7] Redis server went away - trying to reconnect and set data again
[fork 2] [7] Redis server went away - reconnection ok, setting data failed
[fork 2] [8] Redis server went away - trying to reconnect and set data again
[fork 2] [8] Redis server went away - reconnection ok, setting data failed
[fork 2] [9] Redis server went away - trying to reconnect and set data again
[fork 2] [9] Redis server went away - reconnection ok, setting data failed
```

**Comment by eeroniemi** [comment] 2016-04-27 14:25
Okay, seems like my test script had a bug - I didn't pass $host, $port and $timeout to the closure. With that fix it seems like this workaround could actually work. Fixed script:

```php
<?php

/**
 * Utility class to easily fork processes (Adapted for phpredis/phpredis - Issue #70)
 */
class Forker
{
	private $childProcesses = [];

	public function fork($callback)
	{
		$sockets = stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP);
		$pid = pcntl_fork();

		if ($pid === -1) {
			throw new \Exception('Could not fork process');
		} elseif ($pid) {
			fclose($sockets[1]);
			$this->childProcesses[] = [
				'pid'    => $pid,
				'socket' => $sockets[0]
			];
		} else {
			fclose($sockets[0]);
			$return = $callback();

			if (fwrite($sockets[1], serialize($return))) {
				fclose($sockets[1]);
			}

			exit(0);
		}

		return $pid;
	}

	public function wait()
	{
		foreach ($this->childProcesses as $index => $childProcess) {
			pcntl_waitpid($childProcess['pid'], $status, WUNTRACED);

			if ($status > 0) {
				throw new \Exception('Child process exited unclean');
			}

			unset($this->childProcesses[$index]);
		}
	}

}

//////////////////////////////////////////////////////////////////////////////////////////////
// PHP CLI Runner
//////////////////////////////////////////////////////////////////////////////////////////////
$host = '127.0.0.1';
$port = 6379;
$forks = 3;
$iterationsPerFork = 10;
$timeout = 2;

$redis = new \Redis();
$redis->connect($host, $port, $timeout);

$forker = new \Forker();

function setRedisData($redis, $key, $data, $i, $idx) {
	if (! $redis->setex($key, 1440, $data)) {
		echo '[fork ' . $i . '] [' . $idx . '] Unable to setex()' . PHP_EOL;
	} else {
		echo '[fork ' . $i . '] [' . $idx . '] ✓' . PHP_EOL;
	}
}

for ($i = 0; $i < $forks; $i++) {
	$forker->fork(function() use ($iterationsPerFork, $forks, $i, $redis, $timeout, $host, $port) {
		for ($idx = 0; $idx < $iterationsPerFork; $idx++) {
			$key = 'S:' . md5(uniqid($i . $idx, true));
			$data = 'small-data';
			try {
				setRedisData($redis, $key, $data, $i, $idx);
			} catch (\Exception $e) {
				echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - trying to reconnect and set data again' . PHP_EOL;

				try {
					unset($redis);
					$redis = new \Redis();
					$redis->connect($host, $port, $timeout);
				} catch (\Exception $e) {
					echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - reconnection attempt failed' . PHP_EOL;
				}

				try {
					setRedisData($redis, $key, $data, $i, $idx);
				} catch (\Exception $e) {
					echo '[fork ' . $i . '] [' . $idx . '] ' . $e->getMessage() . ' - reconnection ok, setting data failed' . PHP_EOL;
				}
			}
		}
	});
}
$forker->wait();
```

Output:

```
[fork 0] [0] ✓
[fork 0] [1] ✓
[fork 0] [2] ✓
[fork 0] [3] ✓
[fork 0] [4] ✓
[fork 0] [5] ✓
[fork 0] [6] ✓
[fork 0] [7] ✓
[fork 0] [8] ✓
[fork 0] [9] ✓
[fork 1] [0] ✓
[fork 2] [0] ✓
[fork 2] [1] ✓
[fork 1] [1] read error on connection 1 - trying to reconnect and set data again
[fork 2] [2] ✓
[fork 2] [3] ✓
[fork 1] [1] ✓
[fork 2] [4] ✓
[fork 1] [2] ✓
[fork 2] [5] ✓
[fork 2] [6] ✓
[fork 1] [3] ✓
[fork 2] [7] ✓
[fork 2] [8] ✓
[fork 1] [4] ✓
[fork 2] [9] ✓
[fork 1] [5] ✓
[fork 1] [6] ✓
[fork 1] [7] ✓
[fork 1] [8] ✓
[fork 1] [9] ✓
```

Notice these two lines - connection fails:

```
[fork 1] [1] read error on connection 1 - trying to reconnect and set data again
```

And then on re-try it's able to store the data:

```
[fork 1] [1] ✓
```

Comments?

**Comment by virgofx** [comment] 2016-04-27 15:30
@eeroniemi Yes, creating a new redis connection on error per fork will work. This is only a tentative  workaround, albeit, quite ugly :/ High throughput systems that have lots of forks may not have the option of opening up tons of connections - It would be better to fix this server side as this would also improve performance as well.

**Comment by eeroniemi** [comment] 2016-04-28 07:21
@virgofx I think this is reasonable trade-off if you're using non-persistent connections. I haven't tried persistent connections so don't really know how this workaround works under those conditions.

Our PHP app is running on top of nginx + php-fpm (via fastcgi), and we use non-persistent connections to Redis. During last 40 hours we've had on average 126.000 calls (set + get + connect + del) to Redis per minute, and this error has happened twice, so that is 2 times out of 30M+ calls. At this rate my workaround doesn't basically affect the performance at all.

**Comment by Shreeshag** [comment] 2016-07-01 07:48
Hi there,

This works like a charm for me :-)

No configuration changes required 

Try this below code 

```
$redis = new Redis();
ini_set('default_socket_timeout', -1);
 $redis -> pconnect('localhost', 6379);
```

**Comment by tmuras** [comment] 2016-11-27 17:23
I have the same issue with "read error on connection" - with centos, PHP7 (4 web nodes), Redis 3.2.5 - and I strongly suspect it's a network/system issue and connections are dropped outside of Redis and phpredis library.
I can reproduce it with CLI script similar to one from eeroniemi and the only work-around I have at the moment is the same - to re-open the connection and re-try.

**Comment by Tomdarkness** [comment] 2016-12-15 13:50
We've just started running into this issue. However, all we've done is upgrade from PHP 5.6 to 7.1. It's running on the same servers (EC2), connecting to the same redis server (Elasticache). Not changed any Redis/PHP configuration or any code related to Redis.

We started seeing these errors literally as soon as we started the 7.1 rollout.

**Comment by vingrad** [comment] 2017-02-10 23:13
@Tomdarkness  do you have any solution?

**Comment by andygrunwald** [comment] 2017-02-12 11:32
Hey,

this issue is not an easy one. I think we all agree. Even more: This issue is different from setup to setup. We had issues with this in the past as well. In the meantime we solved all of them. We wrote down our experience in our blog. Checkout [Learn Redis the hard way (in production)](http://tech.trivago.com/2017/01/25/learn-redis-the-hard-way-in-production/).

This should not be an advertisement. More some information that might help someone of you to get rid of this issue in your setup.

**Comment by virgofx** [comment] 2017-03-28 13:42
@andygrunwald Issues still persist when forking especially and not mentioned in your nice writeup. There is a clear script to reproduce the problem listed above (https://github.com/phpredis/phpredis/issues/70#issuecomment-151607739)  @michael-grunder  curious as to why this still hasn't been addressed?

**Comment by yatsukhnenko** [comment] 2017-03-29 14:32
Hey, I can reproduce this issue locally so I'll try to find the reason and fix it

**Comment by yatsukhnenko** [comment] 2017-03-29 20:43
Unfortunately TravisCI is not available and I can't test my changes, so I'll continue tomorrow

**Comment by yatsukhnenko** [comment] 2017-03-30 12:02
Who can test a patch?
```
diff --git a/library.c b/library.c
index 9256005..f5463d2 100644
--- a/library.c
+++ b/library.c
@@ -2102,9 +2102,12 @@ redis_sock_gets(RedisSock *redis_sock, char *buf, int buf_size,
         return -1;
     }
 
+    again: *line_size = 0;
     if(php_stream_get_line(redis_sock->stream, buf, buf_size, line_size) 
                            == NULL) 
     {
+        int err = php_socket_errno();
+        if (*line_size == 0 && (err == EAGAIN || err == EWOULDBLOCK)) goto again;
         // Close, put our socket state into error
         REDIS_STREAM_CLOSE_MARK_FAILED(redis_sock);
```

**Comment by yatsukhnenko** [comment] 2017-04-11 15:54
Hey there, I need a feedback :)

**Comment by patademahesh** [comment] 2017-04-27 06:11
We too facing the same issue. @yatsukhnenko does this patch fixes this issue?

**Comment by yatsukhnenko** [comment] 2017-04-27 06:16
@patademahesh, It should :)

**Comment by yatsukhnenko** [comment] 2017-04-27 06:19
I'm going to rewrite this patch without `goto` and merge if it fixes issue for everyone but I'm still waiting for feedback.

**Comment by viion** [comment] 2017-05-13 09:25
@yatsukhnenko how would I be able to test it? 

I get this error every day for the past year, driving me insane!

**Comment by yatsukhnenko** [comment] 2017-05-13 09:32
@viion you should apply the patch I've listed to the source code and compile extension

**Comment by matteomartinelli** [comment] 2017-05-13 14:35
Hey guys,
I read most of the issue but I didnt find any solution: I'm trying to subscribe to a redis channel but after a fixed amount of time it crashes.

suggestion?

**Comment by yatsukhnenko** [comment] 2017-05-13 14:49
@matteomartinelli, definitely you are doing something wrong 😂

**Comment by matteomartinelli** [comment] 2017-05-13 14:50
@yatsukhnenko There's no logic inside my callback, it raises a `PHP Fatal error:  Uncaught RedisException: read error on connection`

**Comment by matteomartinelli** [comment] 2017-05-13 15:24
I misunderstood the `$timeout` parameter in pconnect method. I thought it would raise an exception after `timeout` seconds.

BTW, Solved.

**Comment by dermanov-ru** [comment] 2017-06-13 21:07
in my CLI php script was this line
`// ini_set('default_socket_timeout', 0); // DOESNT WORK WITH REDIS!!!`
just remove of them - solve problem.

**Comment by virgofx** [comment] 2017-06-13 21:59
@yatsukhnenko Is there anyway you can test with the code in issue: comment: https://github.com/phpredis/phpredis/issues/70#issuecomment-151607739.... and confirm failure as outlined in the issue and then with your fix, confirm that it's fixed?

**Comment by yatsukhnenko** [comment] 2017-06-14 09:20
@virgofx, are you asking me to test my own patch? :joy:

**Comment by viion** [comment] 2017-06-14 12:06
@yatsukhnenko i couldn't get your patch working, or it didn't fix my issue. Not sure how to confirm. My issue was happening nearly every day for about 15 minutes I'd get the error. 

I modified my `pconnect` timeout to `5` seconds, and now I get this error a couple times at week, which is an improvement. I also have try/catch connect.

I can deal with it a few times a week since its self-recovery. This is on a site that does about 4000-5000 interactions with Redis every minute (about 80% get GETs). I do not know if that has any effect.

**Comment by virgofx** [comment] 2017-06-14 13:18
@yatsukhnenko Yes :) Simply because it's probably easier for you once patch built to `php redis-test.php` than for those who don't work in redis land to try and pull, build, install, copy patch changes, rebuild, etc.

The script is literally self-contained in that comment.

**Comment by yatsukhnenko** [comment] 2017-06-14 13:59
@virgofx, I've used your test script while created patch

**Comment by yatsukhnenko** [comment] 2017-06-14 14:03
@viion `ini_set('default_socket_timeout', -1);` also doesn't help?

**Comment by finelog** [comment] 2017-07-12 13:16
hey, guys

I am using 3.1.2 version and encountered this issue too, using `ini_set('default_socket_timeout', -1);` works. 

but it's affecting the whole php process life cycle, so I did some digging, and found this
`$redis->setOption(Redis::OPT_READ_TIMEOUT, -1);`. just hope it would help.

**Comment by itbdw** [comment] 2017-07-14 12:45
I'm using predis, I solved the problem several days ago.

I set the redis server timeout to a none zero value. 

What I found is my redis server hold some long time idle connections, when the client try to new connection, error comes out. 

So after I set the timeout, redis serve kill the outdated connection, and here comes peace. Hope helps :)

**Comment by PuShaoWei** [comment] 2017-10-10 04:06
@itbdw 您说的`predis` 是`phpredis` 扩展还是其他什么新的东西呢？据我所知，设置`ini_set('default_socket_timeout', -1);`会导致`file_put_getcontents`始终挂起导致此次请求超时，您所说的杀死进程具体是什么样的可以分享一下吗

**Comment by yatsukhnenko** [comment] 2017-12-04 15:33
Closing this issue as it is too old and contains a lot of unnecessary information...
Lets say that `ini_set('default_socket_timeout', -1);` and `$redis->setOption(Redis::OPT_READ_TIMEOUT, -1);` fixes it :smile: 
Please open new issue If somebody can reproduce `read error on connection` with the latest stable or develop version of phpredis.

**Closed by yatsukhnenko** 2017-12-04 15:33 UTC
Labels: need feedback

**Comment by PuShaoWei** [comment] 2017-12-05 01:28
```
ini_set('default_socket_timeout', -1)
```
Ashamed, however, do not solve the problem :astonished:

```
php-version: PHP 5.5.25 
phpredis-version: 2.2.8.1-2.el6
redis> info
# Server
redis_version:2.8.20
```

**Comment by hubiter** [comment] 2018-04-10 10:09
very good~

**Comment by mowny** [comment] 2020-10-28 12:56
Is this for all sockets or just tcp?
Because we're using unix socket /var/run/redis/redis.sock and still get `PHP Fatal error:  Uncaught RedisException: read error on connection` sporadically
