### ISSUE TITLE
 'read error on connection'

### ISSUE THREAD

**Issue by info2000** [phpredis/phpredis#492] opened 2014-08-03 13:06 UTC
Hi, how can solve this error?
PHP message: PHP Fatal error:  Uncaught exception 'RedisException' with message 'read error on connection'
i'm getting it for this call:  Redis->hGet('fechainicio', '1')

My system is:
PHP Version 5.4.4-14+
in phpinfo redis version 2.2.5 but in redis-cli redis_version:2.6.17
with 17 clients connected, take 6 seconds to show the command prompt when type redis-cli

 Memory
used_memory:91931192
used_memory_human:87.67M
used_memory_rss:105947136
used_memory_peak:5178554456
used_memory_peak_human:4.82G
used_memory_lua:31744
mem_fragmentation_ratio:1.15
mem_allocator:jemalloc-3.2.0

Not save to disk
Thanks

**Comment by andygrunwald** [comment] 2015-05-29 12:53
Should we close this in case of duplicate of https://github.com/phpredis/phpredis/issues/70 ?

**Comment by Evandar276** [comment] 2017-02-13 11:11
I have just discovered that this error pops out when I send redis request after this: `set_time_limit(600);`

I have redis running normally, but this breaks it every time. Is it correct behavior, or bug in phpredis?

**Comment by jgimeno** [comment] 2017-02-24 12:57
I am having this same problem, as @Evandar276 is saying. Is this an issue with the module?

**Comment by muayyad-alsadi** [comment] 2017-07-05 11:13
> Got the same error with $redis->subscribe(array($channel), 'callback'); The weird thing is, the callback function was fired.

@folkenfanel this was the solution from our side (php)

```
      ini_set("default_socket_timeout", -1);
```

**Comment by Devying** [comment] 2017-08-15 06:30
set redis connect timeout=0 and
`ini_set("default_socket_timeout", -1);`

**Comment by yatsukhnenko** [comment] 2017-10-19 14:49
Duplicate #70

**Closed by yatsukhnenko** 2017-10-19 14:49 UTC

**Comment by Ben-Mack** [comment] 2022-12-08 04:15
On Windows with Kaspersky installed, disable `Network Attack Blocker` fixed it for me.

I've tried both Predis and PhpRedis but still error:
`read error on connection to 127.0.0.1:6379` or `Error while reading line from the server. [tcp://127.0.0.1:6379]`

The only way is disable `Network Attack Blocker` (Kaspersky doesn't even show any events in report, but it blocks redis somehow)
