### ISSUE TITLE
rawCommand converts FT.SEARCH property names to bool(true)

### ISSUE THREAD

**Issue by marcing** [phpredis/phpredis#1550] opened 2019-04-29 23:59 UTC
### Expected behaviour
```
127.0.0.1:6379> FT.SEARCH index @keyword:lorem
1) (integer) 1
2) "15cc7874676f73"
3)  1) news_id
    2) "17887"
    3) provider
    4) "Test"
    5) province
    6) "3"
```
### Actual behaviour
```
->rawCommand('FT.SEARCH', 'index', '@keyword:lorem')
array(3) {
  [0]=>
  int(1)
  [1]=>
  string(14) "15cc7874676f73"
  [2]=>
  array(12) {
    [0]=>
    bool(true)
    [1]=>
    string(5) "17887"
    [2]=>
    bool(true)
    [3]=>
    string(6) "Test"
    [4]=>
    bool(true)
    [5]=>
    string(1) "3"
```
### I'm seeing this behaviour on
- OS: Ubuntu
- Redis: 4.0.11
- PHP: 7.3.3
- phpredis: 4.3.0
- RediSearch 1.4.2

I have no clue what might the the origin of this.

**Comment by michael-grunder** [comment] 2019-04-30 00:27
Hi, this is a known limitation of phpredis.  Essentially, with the exception of specific `STREAM` commands, any simple string reply is simply treated as `true`.

We've got a feature branch where this is configurable [here.](https://github.com/phpredis/phpredis/commits/string-reply-literal)

I think it may be worth reviving the feature, but I'd prefer to do it in a way that is backward compatible.

**Comment by marcing** [comment] 2019-04-30 08:19
Dear Michael,

It would be probably enough for my case if FT.* commands had a different behaviour (for compatibility with RediSearch). I don't think it would break anything, since RediSearch does not work because of this. 
Thanks for the hint with the client - I will try another.
It would be great to use one client for connecting to Redis in future.
RediSearch is only going to be more popular and more people will encounter this issue.

Thank you!
Marcin

**Comment by marcing** [comment] 2019-04-30 08:20
https://github.com/phpredis/phpredis/commit/e8a91245ac11b897e8f71c7dd90e4413b6f19c60
This would also work, why isn't it integrated yet into main branch?

**Comment by Budapresst** [comment] 2019-05-10 05:09
+1 for this "improvement"...   The problem is a nightmare because not only are there no key values, but also the data is returned in a different order every time there is a re-index... So essentially there is no way to use redisearch with phpredis...  I'm now having to write code to parse data out of a redis-cli command via shell_exec()...  It's an expensive operation because I can't keep a persistent connection to the redis db using this approach... :(

**Comment by michael-grunder** [comment] 2019-05-10 05:41
I'm planning on getting this merged over the weekend.  I'll link to the issue when it's up.

**Comment by Budapresst** [comment] 2019-05-10 05:52
Wow!  Fantastic!  Thanks, Michael!

**Comment by marcing** [comment] 2019-05-10 08:02
Budapresst - I managed to make it work with:
https://github.com/cheprasov/php-redis-client
It works with Redis 5.0
So I am using two clients at the moment, but it's doing what it should.

**Comment by Budapresst** [comment] 2019-05-10 08:26
Thanks for the tip, Marcin...  I'll check that client out if Michael can't get it sorted in the next week or so... :)

**Comment by michael-grunder** [comment] 2019-05-13 01:59
Hey everyone,

I've uploaded a version with the new option that will tell phpredis not to translate simple string replies into boolean values.

That being said, I didn't need it for `FT.SEARCH` since those fields are returned using BULK strings, which shouldn't get turned into bools.

I did need it for things like `FT.INFO`:

```php
$obj_r->setOption(Redis::OPT_REPLY_LITERAL, true);
print_r($obj_r->rawCommand('FT.INFO', 'idx'));
```

If you still have issues with `FT.SEARCH` please create a small self-contained script which replicates the issue.

**Comment by Budapresst** [comment] 2019-05-13 08:57
Hi Michael,

I tested the new version and it still doesn't work.  I'm using the PECL 4.3 version and this new version built as 4.2 (I don't know if that's an issue).  Anyway... Once you have the Redis 5x running with redisearch.so loading as well, then testing is dead simple:

<?php 
$redis = new Redis();
$redis->connect('127.0.0.1', 6379);
$redis->auth('password');  //if relevant		
$redis->select(0);
$result = $redis->rawCommand("FT.CREATE", "myIdx", "SCHEMA", "title", "TEXT", "WEIGHT", "5.0", "body", "TEXT", "url", "TEXT");
$result = $redis->rawCommand("FT.ADD", "myIdx", "doc1", "1.0", "FIELDS", "title", "hello world", "body", "lorem ipsum", "url", "http://redis.io");
$result = $redis->rawCommand("FT.SEARCH","myIdx","'hello world'");
var_dump($result);
?>
You should get an array with boolean values instead of the key values (title, body, url).

**Comment by yatsukhnenko** [comment] 2019-05-13 09:12
@Budapresst you should use version from GitHub. We haven't released this feature on PECL yet.

**Comment by Budapresst** [comment] 2019-05-13 09:16
@yatsukhnenko Of course... I used this one: phpredis-865651d5586333168ade92ad153a91d4fac96451  I'm only mentioning PECL because the latest version there is 4.3.0, but when I downloaded this new build and ran "make" the version of phpredis now shows as 4.2 instead of 4.3... (I'm not sure if this is important, but I thought it might be worth mentioning)...

**Comment by yatsukhnenko** [comment] 2019-05-13 09:29
Didn't you forget to call `setOption(Redis::OPT_REPLY_LITERAL, true);` before sending raw command?

**Comment by Budapresst** [comment] 2019-05-13 09:49
@yatsukhnenko  YES!  I didn't set that option because I thought it was somehow only relevant to @michael-grunder's test with FT.INFO...   

It works!  This is great, many thanks to both of you! 

Once this is fully tested/accepted, will this be available as a PECL install?  Most of my sites run on cPanel servers, so I prefer to keep things running via their procedures.

**Comment by yatsukhnenko** [comment] 2019-05-13 10:33
This feature will be released with upcoming version 5.0. When? I don't have answer :)

**Comment by Budapresst** [comment] 2019-05-13 10:57
Okay, Thank you!

**Comment by marcing** [comment] 2019-05-13 11:16
Thank You michael-grunder & yatsukhnenko!

**Comment by michael-grunder** [comment] 2019-05-13 16:40
I'm glad it works for everyone!  

We'll release it as part of our 5.0 release on PECL.

**Closed by michael-grunder** 2019-05-13 16:40 UTC
Labels: improvement
