### ISSUE TITLE
hScan return value doesn't always match php method signature

### ISSUE THREAD

**Issue by jc21** [phpredis/phpredis#1923] opened 2021-02-03 23:45 UTC
### Expected behaviour

As per [hScan documentation](https://github.com/phpredis/phpredis/#hscan), the function should *always* return an array.

### Actual behaviour

It is observed that the method returns false when the hash doesn't have anything set, which makes sense.

Further to this, phpstan and probably the php compiler recognises that this hScan function should only return an array. The method return signature in the extension is probably defining this.

### I'm seeing this behaviour on
- OS: Linux
- Redis: 6.0.10
- PHP: 7.4.14
- phpredis: 5.3.2

### Steps to reproduce, backtrace or example script

```php
<?php

$r = new \Redis();
$r->connect('127.0.0.1');
$r->setOption(Redis::OPT_SCAN, Redis::SCAN_RETRY);
$r->hSet('abc123', 'myfield', 'myvalue');

$it = null;

print 'Test #1:' . PHP_EOL;
var_dump($r->hScan('myfield', $it));

print PHP_EOL;

print 'Test #2:' . PHP_EOL;
var_dump($r->hScan('myfield2', $it));

$r->close();
```

OUTPUT:
```
Test #1:
array(0) {
}

Test #2:
bool(false)
```

### I've checked
- 👍  There is no similar issue from other users
- 👍  Issue isn't fixed in `develop` branch

### Final note

The fix for this can either be as per documentation or to fix the method signature to correctly state the returning of FALSE as an option. Either way works for me.

**Comment by michael-grunder** [comment] 2022-09-23 06:16
Closing this in favor of #1921.

There's a draft PR #2015 to fix these, the issue is it likely requires a major version bump.

**Closed as completed by michael-grunder** 2022-09-23 06:16 UTC
