### ISSUE TITLE
phpredis segfaults for NULL values on PHP 5.6.2 (worked on 5.5)

### ISSUE THREAD

**Issue by jwatte** [phpredis/phpredis#524] opened 2014-10-31 17:09 UTC
his PHP code crashes the host (Apache) with a segfault:

$myRedis->hSet("some key name", NULL);
This is troubling to me, because PHP is supposed to be a high-level language that doesn't dereference NULL pointers, but instead either accepts them as "empty value" or throws an exception.

Am I the only one seeing this? (This code worked fine in PHP 5.3 and 5.5)

**Comment by meo-tech** [comment] 2015-03-13 22:15
I can confirm this.
Null Values are Bad under PHP5.6

Code worked like a charm under PHP5.5....

**Comment by michael-grunder** [comment] 2015-03-13 22:17
Sorry everybody, I totally forgot about this one (I am literally the worst).  I'll sort this over the weekend for sure!

Cheers guys!
Mike

**Comment by niborb** [comment] 2015-04-09 13:12
Is there already a fix available?

**Comment by madhancock** [comment] 2015-06-22 12:34
Seems to be working on 2.2.7 with php 5.6 on Deb 8. @michael-grunder please can you confirm that a patch went in for this and it is in the 2.2.7 release?

**Comment by das-peter** [comment] 2015-07-03 09:40
I can confirm that an update from phpredis 2.2.5 to 2.2.7 on Ubuntu 14.04.2 LTS solved this / a similar problem.
The issue was with a boolean value instead NULL but otherwise the same.
Details (including parts of a core dump & stracktrace) can be found here: https://www.drupal.org/node/2522966

Cheers
Peter

**Comment by iprok** [comment] 2015-11-17 11:21
I confirm the issue in debian jessie with php5-redis 2.2.5-1

**Comment by ulwanski** [comment] 2016-03-09 19:37
I can also confirm this error on _Debian 8.3_, **php5-redis 2.2.5-1 and PHP 5.6**.

**Comment by tudor2004** [comment] 2016-04-07 10:34
Could you please provide a fix for this issue? w. PHP 5.5 works find, PHP 5.6.2 crashes

**Comment by NerdyProjects** [comment] 2016-04-21 09:41
I also and still want to confirm this for
php5-cli                             5.6.19+dfsg-0+deb8u1
php5-redis                         2.2.5-1
Debian GNU/Linux 8

As I could not find any backtrace via google, I post it here as well:

Program received signal SIGSEGV, Segmentation fault.
_zend_mm_free_int (heap=0x7ffff7e9f048, p=0x7ffff7e9f058) at /build/php5-5.6.19+dfsg/Zend/zend_alloc.c:2104
2104    /build/php5-5.6.19+dfsg/Zend/zend_alloc.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  _zend_mm_free_int (heap=0x7ffff7e9f048, p=0x7ffff7e9f058) at /build/php5-5.6.19+dfsg/Zend/zend_alloc.c:2104
#1  0x00007fffed3f422a in zim_Redis_set () from /usr/lib/php5/20131226/redis.so

What I am doing is a simple redis->set('some_key', false);
it crashes on the first opportunity :-)

Managing to build the 2.2.7 php-redis with using the unstable source package as a base was a pain in the ass because of the changes for php7 (in the debian package). Anyway, the bug is gone and all works now.

I will raise this in the debian bugtracker again.

**Comment by rbraband** [comment] 2017-01-29 19:43
Thank you for Fixing that.
Today I search around wh my Code hang up aftre moved Server from PHP5.5 to 5.6.
I run a cli bot and my syslog fetch the Errors:
``kernel: [278690.483580] traps: php[661] general protection ip:6cf088 sp:7ffee4c66390 error:0 in php5[400000+7f5000]``
I fix araound 5 issues with _NULL_ and than I have many values with true/false ... but I found there is an update... 2.2.8 solved my Problems :)

**Closed** 2017-02-09 05:24 UTC

**Comment by Rambomst** [comment] 2017-12-09 21:52
I appear to be getting this issue on the latest version.

OS: FreeBSD 10.3-RELEASE
PHP: 5.6.19 
phpredis: 3.1.4
Redis: 3.2.10

The code I run to reproduce the issue:
`$redis->set('key', null, 1000);`
OR
`$redis->set('key', null, ['NX', 'EX' => 1000]);`

**Comment by yatsukhnenko** [comment] 2017-12-10 07:37
@Rambomst I can't reproduce this segfault locally on Linux. Tomorrow I will try on FreeBSD. Could you open new issue and provide test script and backtrace?

**Comment by Rambomst** [comment] 2017-12-10 21:44
@yatsukhnenko In the process of getting that information for you I updated xdebug to the latest version and now I am unable to replicate the seg fault. If it comes back I will open an issue with backtraces etc.
