### ISSUE TITLE
When can you release stable version？

### ISSUE THREAD

**Issue by zhangheng0527** [phpredis/phpredis#810] opened 2016-05-20 11:04 UTC
hey,

Man,It's been a year and a half,When can you release stable version？

**Comment by michael-grunder** [comment] 2016-05-20 17:50
Soon?

That being said both the develop and php7 branches are quite stable, and many people are using it in production.

The only thing I need to do is make sure no fixes are in the develop branch and not in the php7 branch.

Then it's just packaging and uploading to pecl.

**Comment by zhangheng0527** [comment] 2016-05-23 02:17
Thanks，
    as we know，redis 3.2 has been released for some time.As one of the new features is geo api,When do you plan to support this new feature?

**Comment by mikehaertl** [comment] 2016-05-30 08:00
Duplicate of #804 and #790.

**Closed** 2016-06-21 07:21 UTC
