### ISSUE TITLE
[5.3.0] undefined symbol: php_hash_bin2hex

### ISSUE THREAD

**Issue by vvhungy** [phpredis/phpredis#1796] opened 2020-07-01 08:57 UTC
Build phpredis 5.3.0, ./configure --enable-redis --disable-redis-session

"**make**" got **WARNING**:
> /root/sources/redis-5.3.0/redis.c: In function ‘redis_random_hex_bytes’:
> /root/sources/redis-5.3.0/redis.c:787:9: warning: implicit declaration of function ‘php_hash_bin2hex’; did you mean ‘zend_hash_find_ex’? [-Wimplicit-function-declaration]
>          php_hash_bin2hex(dst, (unsigned char *)ZSTR_VAL(s), bytes);
>          ^~~~~~~~~~~~~~~~
>          zend_hash_find_ex

"**make test**" got "**undefined symbol**":
> /myserver/php-7.3.19/bin/php: symbol lookup error: /root/sources/redis-5.3.0/modules/redis.so: undefined symbol: php_hash_bin2hex
> /myserver/php-7.3.19/bin/phpdbg: symbol lookup error: /root/sources/redis-5.3.0/modules/redis.so: undefined symbol: php_hash_bin2hex
> /myserver/php-7.3.19/bin/php: symbol lookup error: /root/sources/redis-5.3.0/modules/redis.so: undefined symbol: php_hash_bin2hex

### I'm seeing this behaviour on
- OS: CentOS 8
- PHP: 7.3.19
- phpredis: 5.3.0
- gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**Comment by remicollet** [comment] 2020-07-01 09:11
Looks like your php doesn't have "hash" extension

**Comment by remicollet** [comment] 2020-07-01 09:16
pr #1797 should ensure proper extension load order

**Comment by yatsukhnenko** [comment] 2020-07-01 09:20
@remicollet maybe we can avoid using `php_hash_bin2hex` and store salt as binary string

**Comment by remicollet** [comment] 2020-07-01 09:21
@vvhungy Perhaps you can try pre-build CentOS 8 packages from https://rpms.remirepo.net/

**Comment by remicollet** [comment] 2020-07-01 09:21
> @remicollet maybe we can avoid using php_hash_bin2hex and store salt as binary string

Yes, in this case we can make use of hash conditional, like for json.

**Comment by remicollet** [comment] 2020-07-01 09:24
Also notice that starting with **7.4** hash is always there, and with **8.0** json also.

So don't know if it really worth the change... hash is "mandatory" for lot of things in PHP.

**Comment by yatsukhnenko** [comment] 2020-07-01 09:36
We also use hash in RedisArray so your PR is preferred solution

**Comment by vvhungy** [comment] 2020-07-02 01:09
I'm sure that our PHP build already include hash module.
> /myserver/php/bin/php -m|grep hash
> hash

With the hash checking as @remicollet proposed, I could see "hash" in "configure" output:
> checking use system liblz4... no
> checking for hash includes... /myserver/php-7.3.19/include/php
> checking for json includes... /myserver/php-7.3.19/include/php
> checking for redis json support... enabled

Even with adding the line "**ZEND_MOD_REQUIRED("hash")**" in **redis.c** still got the same WARNING as before.

**Comment by michael-grunder** [comment] 2020-07-02 01:28
Interesting, I'm not sure why you're having trouble but I went ahead and removed the dependency on that function in cd55ef1, which we'll get merged into 5.3.1

**Comment by remicollet** [comment] 2020-07-02 05:04
Sorry, but for me, this really looks like a corrupted dev. env.

> /myserver/php/bin/php -m|grep hash

>  checking for json includes... /myserver/php-7.3.19/include/php

This is not consistent.

BTW, is the header is found the symbol should be there.
else build should fails on not find header

Using PHP on a dev machine (where it is built) seems a bad idea, as everyone know, dev. machine are always a mess. Nothing is reproducible.

**Comment by vvhungy** [comment] 2020-07-02 06:28
@remicollet I built the module on one of our **production** servers, which was successfully built phpredis 5.2.2.

The only different is that our PHP build use a disable-all then enable only needed modules.

Can you try with the following custom PHP configure to figure out what happened?
> './configure'  '--prefix=/myserver/php-7.3.19' '--disable-all' '--with-libdir=lib64' '--enable-ctype' '--with-curl' '--enable-libxml' '--with-pcre-regex' '--with-iconv' '--enable-fpm' '--enable-simplexml' '--enable-xml' '--with-openssl' '--enable-dom' '--enable-json' '--enable-hash' '--with-zlib' '--enable-opcache' '--enable-filter' '--enable-phar'

and phpredis configure:
> ./configure --enable-redis --disable-redis-session --with-php-config=/myserver/php-7.3.19/bin/php-config

Environment
- OS: CentOS 8
- PHP: 7.3.19
- phpredis: 5.3.0
- gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)

**Comment by michbsd** [comment] 2020-07-02 10:22
Hi, 
I successfully built this on FreeBSD (and I have "hash" extension installed) - however when I try to run php after phpredis 5.3.0 installtion - I get: 
/usr/local/lib/php/20170718/redis.so: Undefined symbol "php_hash_bin2hex"

Any ideas? 

In the interim I've rolled back to 5.2.2

**Comment by remicollet** [comment] 2020-07-02 12:08
Finally can reproduce.

You have a php build without "session" extension enabled (how can this be useful ?)
Adding `#include <ext/hash/php_hash.h>` in redis.c solves this issue

When "session" is there, `php_hash.h `is included from `php-session.h`

BTW, shouold be fixed by pr #1800 

> @remicollet I built the module on one of our production servers

If you have "developpement" tools installed this is a developper environment ;)
(usually considered as a very bad idea on a prod server)

Again, on a RPM distro, use RPM, especially when exists

**Comment by michbsd** [comment] 2020-07-02 12:56
Actually - I had both session and hash - but the build threw the following warning:

```
--- redis.lo ---
/var/ports/basejail/usr/ports/databases/pecl-redis/work-php72/redis-5.3.0/redis.c:787:9: warning: implicit declaration of function 'php_hash_bin2hex' is invalid in C99 [-Wimplicit-function-declaration]
        php_hash_bin2hex(dst, (unsigned char *)ZSTR_VAL(s), bytes);
        ^
--- redis_sentinel.lo ---
```

Adding the include to redis.c - fix this, and it seems to work.

**Comment by remicollet** [comment] 2020-07-02 13:06
> Actually - I had both session and hash - but the build threw the following warning:


@michbsd but do you build redis with `--disable-redis-session` or `--enable-redis-session`

**Comment by michbsd** [comment] 2020-07-02 13:36
configure:4127: checking whether to disable sessions
configure:4141: result: yes

**Closed as completed** 2020-07-02 16:47 UTC

**Comment by vvhungy** [comment] 2020-07-03 01:24
@michael-grunder when will we have the next release which includes this fix? If it not a long time then I can wait instead of applying a manual patch :)

**Comment by michael-grunder** [comment] 2020-07-03 03:35
Assuming there are no other bugs reported I think we can release 5.3.1 in the next couple of days.

I just don't want to release it and then immediately get another report (which is 100% what usually happens.  :smile:)
