### ISSUE TITLE
PHP 7.2.2 - No Redis Save Handler

### ISSUE THREAD

**Issue by Littlericket** [phpredis/phpredis#1318] opened 2018-03-05 09:20 UTC
### Expected behaviour
Registered save handlers => files user memcached **redis**

### Actual behaviour
Registered save handlers => files user memcached

### I'm seeing this behaviour on
- OS: Ubuntu 17.10 4.13.0-25-generic
- Redis: v=4.0.2 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=a179593449988b17
- PHP: 7.2.2 (fpm-fcgi)
- phpredis: 4.0.0RC1

### Steps to reproduce, backtrace or example script
Configure php with '--enable-redis' '--enable-redis-igbinary'

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by yatsukhnenko** [comment] 2018-03-05 11:19
Didn't you forget to run `make install`? :)

**Comment by Littlericket** [comment] 2018-03-05 11:21
Nah, I dont think so:

```
php --ri redis

redis

Redis Support => enabled
Redis Version => 4.0.0RC1
Available serializers => php
```

**Comment by remicollet** [comment] 2018-03-05 11:36
Perhaps:

  `make clean; make`

**Comment by Littlericket** [comment] 2018-03-05 11:41
I did that as well.

**Comment by Littlericket** [comment] 2019-01-01 16:32
I know whats the cause now.. it happens when you compile php and enabling redis; like when you move it to the "ext" folder of PHP. You have to phpize and make it seperately.

**Comment by michael-grunder** [comment] 2019-01-31 22:02
Were you able to get it working?

**Comment by Littlericket** [comment] 2019-02-01 17:54
@michael-grunder yeah, it works when cloning this repo and "making" it, instead of putting the phpredis dir into the "php-source/ext" folder and compiling php with --enable-redis.
I don't really know why this happens - if you can explain that to me you can close this.

**Comment by michael-grunder** [comment] 2019-02-04 20:43
I can't explain it.  I have lots of versions of PHP to test PhpRedis that I build from source, but don't see this issue myself.

I don't know a lot about autotools but I regenerate the configure file by doing `./buildconf --force` and then the `./configure` with all of the options.

But if your build gets  you `Redis` then the issue is likely something weirder...

**Comment by michael-grunder** [comment] 2019-06-05 19:03
Closing the issue as it seems to have been resolved.

**Closed by michael-grunder** 2019-06-05 19:03 UTC
