### ISSUE TITLE
Repeated MOVE redirections can cause phpredis to read old data

### ISSUE THREAD

**Issue by michael-grunder** [phpredis/phpredis#1425] opened 2018-10-12 19:20 UTC
Phpredis can get confused by multiple redirections in short order leading to a situation where a command is sent to a given node but not fully consumed.

See #1222 for more context to the problem.

When this happens phpredis will then read old data from the previously sent node and be inconsistent from that point until the connection is reset.

Here is instrumented debugging output to illustrate what is happening:

```bash
[1875]: Sending command to: 10.0.0.7:6379 <-- sends command but detects
                                              error and fails to consume 
                                              full response from server.

[1876]: Sending command to: 10.0.0.5:6379 <-- Starts redirecting for non error.
[1877]: Sending command to: 10.0.0.5:6379     
[1878]: Sending command to: 10.0.0.8:6379

[1879]: Sending command to: 10.0.0.7:6379 <-- reaches 10.0.0.7 again, with the
                                              still unconsumed '1875' reply.

[1879]: Expected '1879' but found '1875'  <-- We read wrong data.
```

I have not tracked down precisely which part of the code is failing (or how) but it's pretty clear what is causing the issue.

I'm opening a new issue since it's related but not really the same problem as was being discussed in #1222.

**Comment by liamsorsby** [comment] 2018-10-14 08:52
It would be worth noting @michael-grunder that I cannot reproduce this issue when persistence is turned off.

**Comment by michael-grunder** [comment] 2018-10-14 19:31
@liamsorsby Please give the branch I just pushed a spin.  I have been running the previously failing code in a loop for an hour with zero failures.

**Comment by liamsorsby** [comment] 2018-10-15 18:20
I'm trying it now @michael-grunder I'll let you know the output

**Comment by liamsorsby** [comment] 2018-10-15 18:30
Also, I'm still using set rather than eval

**Comment by liamsorsby** [comment] 2018-10-15 18:38
Interestingly, @michael-grunder @yatsukhnenko  This bug seems to occur with persistence off as well
```
Key set 127
Testing!
Wrong value found!!
Key: 26
Value: 54```

**Comment by liamsorsby** [comment] 2018-10-15 19:35
Also, should we return 0 on an error here: https://github.com/phpredis/phpredis/blob/develop/cluster_library.c#L1058

**Comment by michael-grunder** [comment] 2018-10-15 20:43
> Also, should we return 0 on an error here: /cluster_library.c@develop#L1058

Yes

Are you sure you're running the newer code?  I can consistently cause wrong reads running 2e412373c47a574a1215756e79e6512a46e30cdc:

```
Phpredis version: 2e412373c47a574a1215756e79e6512a46e30cdc
Setting up test
Testing!
[00:00:04]:  Number of iterations over 1 seconds: 19
[00:00:04]:  Commands: 20, Errors: 0, Exceptions: 0
[00:00:09]:  Number of iterations over 1 seconds: 0
[00:00:09]:  Commands: 20, Errors: 0, Exceptions: 1
[00:00:14]:  Number of iterations over 1 seconds: 13
[00:00:14]:  Commands: 34, Errors: 0, Exceptions: 1
[00:00:20]:  Number of iterations over 1 seconds: 19
[00:00:20]:  Commands: 53, Errors: 0, Exceptions: 2
[00:00:25]:  Number of iterations over 1 seconds: 3
[00:00:25]:  Commands: 56, Errors: 0, Exceptions: 3
[00:00:30]:  Number of iterations over 1 seconds: 24
[00:00:30]:  Commands: 81, Errors: 0, Exceptions: 3
[00:00:35]:  Number of iterations over 1 seconds: 3
[00:00:35]:  Commands: 85, Errors: 0, Exceptions: 3
[00:00:35]: ERROR: 111 != 45 (Phpredis: 2e412373c47a574a1215756e79e6512a46e30cdc)
/* Snip */
[00:02:02]: ERROR: 14 != 98 (Phpredis: 2e412373c47a574a1215756e79e6512a46e30cdc)
```

I cannot under 27df92208a6a7c712ae08407a430059ab8b0d1ad:
```bash
/* Truncated previous hour of no errors ... */
[01:03:06]:  Number of iterations over 1 seconds: 999
[01:03:06]:  Commands: 515,114, Errors: 0, Exceptions: 457
[01:03:11]:  Number of iterations over 1 seconds: 1054
[01:03:11]:  Commands: 516,169, Errors: 0, Exceptions: 457
[01:03:16]:  Number of iterations over 1 seconds: 3
[01:03:16]:  Commands: 516,173, Errors: 0, Exceptions: 457
[01:03:21]:  Number of iterations over 1 seconds: 15
[01:03:21]:  Commands: 516,189, Errors: 0, Exceptions: 457
[01:03:26]:  Number of iterations over 1 seconds: 1012
[01:03:26]:  Commands: 517,201, Errors: 0, Exceptions: 458
[01:03:31]:  Number of iterations over 1 seconds: 568
[01:03:31]:  Commands: 517,770, Errors: 0, Exceptions: 458
```

Maybe this modified [Cluster.php](https://gist.github.com/michael-grunder/c4d33aa8c20ff888912e633056f5ca4a) script can help verify.

**Comment by liamsorsby** [comment] 2018-10-16 11:58
Ahhh, Sorry @michael-grunder I assumed that was on the develop branch. I'll check out the commit directly and attempt it again

**Comment by liamsorsby** [comment] 2018-10-16 12:12
@michael-grunder I also don't seem to be able to replicate the issue with that commit 😄

**Comment by liamsorsby** [comment] 2018-10-16 13:59
```
Phpredis version: 27df92208a6a7c712ae08407a430059ab8b0d1ad
Setting up test
Setting all keys
Key set 0
...
[00:02:00]:  Number of iterations over 1 seconds: 5
[00:02:00]:  Commands: 10,213, Errors: 0, Exceptions: 9
...
[00:06:49]:  Number of iterations over 1 seconds: 1596
[00:06:49]:  Commands: 66,517, Errors: 0, Exceptions: 416
...
[00:26:46]:  Number of iterations over 1 seconds: 2
[00:26:46]:  Commands: 218,681, Errors: 0, Exceptions: 550
...
[01:36:04]:  Number of iterations over 1 seconds: 18
[01:36:04]:  Commands: 864,675, Errors: 0, Exceptions: 962
```
Looks good to me

**Comment by yatsukhnenko** [comment] 2018-10-16 14:11
@michael-grunder could you look at my [comment](https://github.com/phpredis/phpredis/commit/27df92208a6a7c712ae08407a430059ab8b0d1ad#commitcomment-30922591) before merging your changes

**Comment by michael-grunder** [comment] 2018-10-16 15:07
@liamsorsby We've already got a release candidate for 4.2 and I think this issue is probably worth getting into the final release, but I don't have an exact timeframe.  It's better to give sufficient time for testing so we don't have to release two versions quickly.

@yatsukhnenko Yeah I'll make the logic less silly.

**Comment by liamsorsby** [comment] 2018-10-16 18:38
@michael-grunder Okay, well let me know when the logic is re-worked and I'll happily do some testing if it helps speed things up 👍

**Comment by michael-grunder** [comment] 2018-10-19 16:20
@liamsorsby I forgot to include the issue number in the commit, but we think the finalized fix is up in the issue-1425 branch.

Let us know how it goes then we'll get it merged.

**Comment by liamsorsby** [comment] 2018-10-20 10:10
Testing now. I'll update this comment with results @michael-grunder

**Comment by yatsukhnenko** [comment] 2018-10-23 06:08
Merged `issue-1425` into `develop`

**Closed by yatsukhnenko** 2018-10-23 06:08 UTC
