### ISSUE TITLE
`redis.so` has size of 3.6 MB

### ISSUE THREAD

**Issue by mvorisek** [phpredis/phpredis#2077] opened 2022-02-26 22:24 UTC
### Expected behaviour

size less than 1 MB

### Actual behaviour

The redis ext is very large, much larger than complex extensions like `xdebug` or other data libs like `mysqli` or complex Microsoft ODBC.

I belive the size can be investigated, maybe some inline modifiers are overused, or is some heavy lib staticaly compiled in?

**Comment by michael-grunder** [comment] 2022-03-06 23:02
I don't really consider this a bug personally, but I'm not opposed to modifications that would reduce code size.

Aggressive inlining probably isn't the cause, since only a couple of functions are inlined explicitly.  My wild guess as to what contributes to the large size is probably our atomic/pipeline macros, which are inlined by definition for every single method in `Redis` and `RedisCluster`.

**Comment by taka-oyama** [comment] 2022-04-11 05:45
Stripping and discarding symbols using the `strip` command will reduce the so files to 638K.

**Comment by xiaoxiongjie** [comment] 2022-04-11 05:46
您好，现在无法亲自回复您的邮件。我将尽快给您回复。杰祝您工作愉快~

**Comment by michael-grunder** [comment] 2022-10-06 02:01
I'm going to close this as not a bug, but I will try to keep size in mind as we move forward.

**Closed as completed by michael-grunder** 2022-10-06 02:01 UTC
Labels: not a bug
