### ISSUE TITLE
Uncaught exception 'RedisException' with message 'protocol error, got 'g' as reply type byte ' ..... Stack trace: #0 .... Redis->get('my_key')

### ISSUE THREAD

**Issue by mitsus** [phpredis/phpredis#886] opened 2016-07-13 09:59 UTC
Hi,
from yesterday...i've this error on phpredis. Two days ago everything worked fine, but yesterday, suddenly i got this error on my web page.
Itried to remove and reistall redis, php redis, my web interfce, but result is the same.

Please can someone help me?

Best Regards

**Comment by michael-grunder** [comment] 2016-07-13 16:21
Hi,

Could you provide more information please?

The version of Redis, phpredis, and php would be helpful.  Also I see from the issue that the issue is happening on a simple get, but are you able to replicate it in a simple cli script that you run from the command line?  That stuff makes it a lot easier to track down.  

That being said, there is another issue that seems related to this which was posted recently that seems to have to do with upgrading to redis 3.2.0.  Did you recently upgrade redis?

Cheers,
Mike

**Comment by mitsus** [comment] 2016-07-13 16:30
Hi, 
ok sorry.
- PHP Version 5.3.3-7
- Redis Server v. 3.0.4
- Php redis v. 2.2.8-rc1

I'tried to replicate steps that i exec into my php page using redis-cli...and all work fine.
No, i'm not upgrade Redis serve. Do you think that this issue solve this problem?

Thanks

**Comment by yatsukhnenko** [comment] 2016-07-13 19:02
@michael-grunder, I'm looking at `Redis::redis_sock_read`  function and seeing that there is no break in switch statement for `':'` and `+` cases. Is it possible that `inbuf` contains binary data or really short string and execution goes to `default` block?

**Comment by michael-grunder** [comment] 2016-07-13 22:06
@yatsukhnenko I just took a quick look, but I don't _think_ so.  Firstly, get should be returning either a bulk response `$` or a null multibulk response `*` in the case the key doesn't exist.  Even for binary encoded data (unless this has recently changed), redis-server will append `\r\n` to the response, so it's always at least two bytes.  Also, the fact that the reply-type is 'g' leads me to believe this might be a case where phpredis is getting out of sync.

@mitsus Are you using pconnect in a web app for the process?

**Comment by mitsus** [comment] 2016-07-14 10:12
@yatsukhnenko i use connect method: 
`$redis->connect('127.0.0.1');`

**Comment by yatsukhnenko** [comment] 2016-07-14 14:43
@michael-grunder, 
> redis-server will append \r\n to the response, so it's always at least two bytes.

but in code we compare length without this two bytes `*buf_len = strlen(inbuf) - 2;`, so reply `+g\r\n` theoretically(not for this issue) may cause exception :scream_cat:

I agree that this looks like out of sync

**Comment by yatsukhnenko** [comment] 2016-07-14 15:03
Oops, I miss equal in condition

**Comment by michael-grunder** [comment] 2016-07-14 16:59
@mitsus Does this happen every time when running via cgi or just intermittently?  Also what sorts of things are you doing that cause it?  Given that it works in cli, it's not simply a matter of get not working, but must be contextual based on the other things that you're doing.

Do you happen to fork your process, or do anything like that?

**Comment by yatsukhnenko** [comment] 2017-03-28 18:36
Duplicate #831, may be fixed in d0f3d01

**Closed by yatsukhnenko** 2017-03-28 18:36 UTC
