### ISSUE TITLE
 5.2.0RC1 - Persistent connection pooling issue

### ISSUE THREAD

**Issue by Tbone542** [phpredis/phpredis#1712] opened 2020-02-17 22:01 UTC
### Expected behaviour
Script will return data and not `ERR_EMPTY_RESPONSE`.

### Actual behaviour
Am trying 5.2.0RC1. It is installing by default with...
`redis.pconnect.pooling_enabled = 1`

With this enabled, I am getting strange errors.
`org.apache.http.NoHttpResponseException: localdomain.test:443 failed to respond`
in jMeter
and
`ERR_EMPTY_RESPONSE`
in Chrome

I am using RedisCluster with persistent connections set to TRUE.

I am not seeing any exceptions or errors. If I let the browser sit for a while, occassionally it will refresh itself and display the proper data, while other times it will refresh and show the same Empty Response Error.

If I use...
`redis.pconnect.pooling_enabled = 0`

It seems to work properly.

I have also tried 5.0.2 and 5.1.1 with pconnect pooling enabled and they seem to work fine.

### I'm seeing this behaviour on
- OS: Centos
- Redis: 5.05
- PHP: 7.0
- phpredis: 5.2.0RC1

### I've checked
- [ x ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment] 2020-02-17 22:44
Thanks for the report.  A `443` response indicates phpredis is crashing.  The trick is going to be reproducing the problem but I'll give it a go.

**Comment by karock** [comment] 2020-02-17 22:47
I think the :443 in the report above is actually the port his local environment is running on, not an HTTP status code.

**Comment by michael-grunder** [comment] 2020-02-17 23:06
Good point, you would appear correct :smile:

Generally when we see a completely empty response from the web server it's caused by a segfault or similar.

We changed how persistent connections and connection pooling work in this release, so it seems likely this is the issue.  As always, the trick will be reproducing.

**Comment by michael-grunder** [comment] 2020-02-18 06:10
@Tbone542 

I put together a simple test script that uses persistent connections with RedisCluster and have not seen any problems.  The new challenge/response mechanism is working for me as expected.

The complete `redis` section of `phpinfo()` might be useful, but also can you provide more detail about what the script in question is doing?  Perhaps we can narrow down the issue that way.

**Comment by Tbone542** [comment] 2020-02-18 14:29
Tried RC2, same result.

phpredis config
```
Redis Support => enabled
Redis Version => 5.2.0RC2
Redis Sentinel Version => 0.1RC2
redis.arrays.algorithm => no value => no value
redis.arrays.auth => no value => no value
redis.arrays.autorehash => 0 => 0
redis.arrays.connecttimeout => 0 => 0
redis.arrays.consistent => 0 => 0
redis.arrays.distributor => no value => no value
redis.arrays.functions => no value => no value
redis.arrays.hosts => no value => no value
redis.arrays.index => 0 => 0
redis.arrays.lazyconnect => 0 => 0
redis.arrays.names => no value => no value
redis.arrays.pconnect => 0 => 0
redis.arrays.previous => no value => no value
redis.arrays.readtimeout => 0 => 0
redis.arrays.retryinterval => 0 => 0
redis.clusters.auth => no value => no value
redis.clusters.cache_slots => 1 => 1
redis.clusters.persistent => 0 => 0
redis.clusters.read_timeout => 0 => 0
redis.clusters.seeds => no value => no value
redis.clusters.timeout => 0 => 0
redis.pconnect.connection_limit => 0 => 0
redis.pconnect.pooling_enabled => 1 => 1
redis.session.lock_expire => 0 => 0
redis.session.lock_retries => 10 => 10
redis.session.lock_wait_time => 2000 => 2000
redis.session.locking_enabled => 0 => 0
```

script
```
<?php

$redis = new Rediscluster(NULL, Array('192.168.56.101:7001', '192.168.56.101:7002', '192.168.56.101:7003'), 30, 30, true);

$cycles = 5000;
$count = 0;

	for ($y = 1; $y <= $cycles; $y++) {
	
		$res = $redis->hgetall('k2');

		if ($res['testfield'] == 'testvalue'){
			$count++;
		} else {
			echo(microtime()).':';
			echo $y.'-HGETALL-FAIL...';
			var_dump($res);
		}
		
	}

echo $count.'/'.$cycles;

?>
```
The script attempts to access a key 'k2' which is in slot 449 multiple times per http request.   449 was chosen to make it easier to migrate the slot during a resharding, so I didn't have to do a large chunk.

It is easiest to see the issue when I run jmeter and start 20-30 threads(http requests).  This is done, so that I know multiple clients should be requesting the migrating key at a given moment.  This is used to check the MOVED/ASK is working properly.  The 5000 cycles are there so I know there are still clients requesting said key when the target slot is migrated.

After some debugging in PHP, I have found that the error is generated in the http client immediately after `$res = $redis->hgetall('k2');`.  So I believe something is going on during the hgetall, though I have yet been unable to see any errors or exceptions.

I would estimate the varying failure rate to be between 25% and 75%. 

NOTE: These failures occur when the cluster is in a static state and not migrating any keys.

Thanks again,
Ted

**Comment by Tbone542** [comment] 2020-02-18 16:00
Another note: when I run it via the CLI, I occassionally get...
`Segmentation fault`

-Ted

**Comment by michael-grunder** [comment] 2020-02-18 16:07
> Another note: when I run it via the CLI, I occassionally get...
Segmentation fault

This was my guess, thanks.  I'll see if I can cause a problem with `hgetall`

**Comment by Tbone542** [comment] 2020-02-18 16:49
I also got the segfault when I was writing to the cluster with xadd.

**Comment by michael-grunder** [comment] 2020-02-18 19:34
This one is going to be annoying.

I can run your script in a CentOS container against php 7.0.0 and phpredis 5.2.0RC2 under valgrind and see no problem whatsoever.

A stack trace or valgrind output on your end might give us a clue.

**Comment by Tbone542** [comment] 2020-02-18 19:45
Hmmm. I tried a trace earlier and it didn't show much. I may need to change the config on xdebug? I am not a professional with xdebug and traces.

... Found it? Was just typing...

-Ted

**Comment by michael-grunder** [comment] 2020-02-19 01:47
cc @yatsukhnenko do you mind testing 9ef2ed89.

**Comment by yatsukhnenko** [comment] 2020-02-19 13:38
@michael-grunder I've tested your changes locally and ran static analysis via clang and coverity. Everithing seems fine.

**Comment by michael-grunder** [comment] 2020-02-19 18:39
@Tbone542 If you can let me know if the swtich to php_rand from php_mt_rand works for you I'll package up RC2 and get it released.

**Comment by Tbone542** [comment] 2020-02-19 21:37
I found the change and manually applied it locally. Seems to work well. I did a few hundred threads with 0 errors.

-Ted

**Comment by michael-grunder** [comment] 2020-02-24 20:16
Closing this issue as it seems to be fixed.  5.2.0 coming soon!

**Closed by michael-grunder** 2020-02-24 20:16 UTC
