### ISSUE TITLE
php8.1 PHP Fatal error:  Arginfo / zpp mismatch during call of Redis::pconnect() 

### ISSUE THREAD

**Issue by ixqbar** [phpredis/phpredis#2041] opened 2021-12-06 07:05 UTC
```php
<?php

$redis_handle = new Redis();
$redis_handle->pconnect('127.0.0.1', 6379, 30, 'x1');



PHP Fatal error:  Arginfo / zpp mismatch during call of Redis::pconnect() 
```

### I'm seeing this behaviour on
- PHP: 8.1
- phpredis: redis-5.3.5 redis-5.3.6 redis-5.3.7

**Comment by ixqbar** [comment] 2022-02-09 03:56
redis.c
```
ZEND_BEGIN_ARG_INFO_EX(arginfo_pconnect, 0, 0, 1)
    ZEND_ARG_INFO(0, host)
    ZEND_ARG_INFO(0, port)
    ZEND_ARG_INFO(0, timeout)
    ZEND_ARG_INFO(0, persistent_id)
    ZEND_ARG_INFO(0, retry_interval)
    ZEND_ARG_INFO(0, read_timeout)
ZEND_END_ARG_INFO()
```


@michael-grunder @yatsukhnenko

**Comment by matysekmichal** [comment] 2022-03-05 15:51
I had the same problem. For me it worked to compile php without the `--enable-debug` flag.

**Comment by michael-grunder** [comment] 2022-10-13 19:19
Closing as I believe this is fixed in the develop branch.  If you still see this issue please reopen.

**Closed as completed by michael-grunder** 2022-10-13 19:19 UTC

**Comment by Fryuni** [comment] 2023-04-05 18:44
This problem still happens when php was compiled with `enable-debug`.

We cannot profile applications that use this extension since profiling requires debug symbols to work.

Although there hasn't been any release since Michael's comment.

**Comment by alcohol** [comment] 2023-05-03 14:26
I second what @Fryuni said. Do we need to open a new issue? Can this one be reopened? The issue is still present.

**Comment by ClosetMonkey** [comment] 2023-07-11 07:06
It's cheezie work to see a problem automagically disappear and then consider it good. I'm seeing the same issue.

**Comment by ClosetGeek-Git** [comment] 2023-07-11 07:54
Food for thought:
`ZEND_BEGIN_ARG_INFO_EX(arginfo_pconnect, 0, 0, 1)` means only 1 parameter (the first) is required. This is handled by `zend_parse_method_parameters` as follows with the parameter list of "Os|lds!lda"
```
zend_parse_method_parameters(ZEND_NUM_ARGS(), getThis(),
                                     "Os|lds!lda", &object, redis_ce, &host,
                                     &host_len, &port, &timeout, &persistent_id,
                                     &persistent_id_len, &retry_interval,
                                     &read_timeout, &context)
```
The list above declares two parameters that are required then 5 that are optional. I know the first parameter in "Os|lds!lda" is the object that the method is called on and is passed using `getThis()` rather than as a method parameter, but the arginfo doesn't seem to match the actual parameter list.

**Comment by VVD** [comment] 2023-07-11 12:16
Same here:
```
PHP Fatal error:  Arginfo / zpp mismatch during call of Redis::pconnect() in nextcloud/lib/private/RedisFactory.php on line 137
```
This line of the `nextcloud/lib/private/RedisFactory.php`:
```
$this->instance->pconnect($host, $port, $timeout, null, 0, $readTimeout);
```
Environment:
* FreeBSD 13.2-p1 amd64
* php 8.1.21
* php81-pecl-redis-5.3.7
* redis 7.0.12
* nextcloud 27.0.0.8

`nextcloud/config/config.php` with unixsocket:
```
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => [
      'host' => '/var/run/redis/redis.sock',
      'port' => 0,
  ],
```
`nextcloud/config/config.php` with tcp:
```
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => [
      'host' => '127.0.0.1',
      'port' => 6379,
      'timeout' => 0.0,
  ],
```

**Comment by VVD** [comment] 2023-07-11 12:33
> Closing as I believe this is fixed in the develop branch. If you still see this issue please reopen.

Can you please point to commit with fix this bug?
Thanks.

**Comment by VVD** [comment] 2023-07-11 13:01
Look like this one: https://github.com/phpredis/phpredis/commit/7cc15ca2093ffb72968cc7aec550ef98fa0f94ec
AFAIU, it's very hard to apply it to last release 5.3.7.
So request for new release - 5.3.8…

**Comment by VVD** [comment] 2023-07-11 13:08
Oh, missed 2nd post.
So for me workaround is to build with simple patch:
```
--- redis.c.orig        2022-02-15 18:25:22 UTC
+++ redis.c
@@ -154,6 +154,9 @@ ZEND_BEGIN_ARG_INFO_EX(arginfo_pconnect, 0, 0, 1)
     ZEND_ARG_INFO(0, host)
     ZEND_ARG_INFO(0, port)
     ZEND_ARG_INFO(0, timeout)
+    ZEND_ARG_INFO(0, persistent_id)
+    ZEND_ARG_INFO(0, retry_interval)
+    ZEND_ARG_INFO(0, read_timeout)
 ZEND_END_ARG_INFO()
 
 ZEND_BEGIN_ARG_INFO_EX(arginfo_mget, 0, 0, 1)
```
