### ISSUE TITLE
Which file need to include 

### ISSUE THREAD

**Issue by bytecodedhawal** [phpredis/phpredis#1606] opened 2019-07-18 15:00 UTC
Hello
which file i need include it...
Can you help me out...
it will worked pusub, for real time application

### I'm seeing this behaviour on
- OS: 
- Redis:
- PHP:
- phpredis:

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment] 2019-07-18 16:43
Hi,

PhpRedis is a PHP extension so you don't need to include any files inside of your PHP script.  You need to add it to your PHP installation.

Here are the [installation instructions](https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown)

If you compile from source you'll need to find where PHP looks for additional INI files and create one with `extension=redis.so` in it.

You can find these files by doing this:

```bash
➜  $ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php/5.6
Loaded Configuration File:         /usr/local/etc/php/5.6/php.ini
Scan for additional .ini files in: /usr/local/etc/php/5.6/conf.d
Additional .ini files parsed:      /usr/local/etc/php/5.6/conf.d/ext-igbinary.ini,
/usr/local/etc/php/5.6/conf.d/ext-mcrypt.ini,
/usr/local/etc/php/5.6/conf.d/ext-mongo.ini,
/usr/local/etc/php/5.6/conf.d/ext-msgpack.ini,
/usr/local/etc/php/5.6/conf.d/ext-opcache.ini,
/usr/local/etc/php/5.6/conf.d/ext-redis.ini,
/usr/local/etc/php/5.6/conf.d/ext-seext.ini,
/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini,
/usr/local/etc/php/5.6/conf.d/ext-xhprof.ini,
/usr/local/etc/php/5.6/conf.d/ext-yaml.ini
```

In my case it's in this file:
```bash
$ cat /usr/local/etc/php/5.6/conf.d/ext-redis.ini
[redis]
extension=redis.so
```

Then to check that it's installed you can do `php -m|grep redis`.

**Comment by michael-grunder** [comment] 2019-07-19 16:32
@bytecodedhawal Going to close this issue since it's not a bug in PhpRedis, but if you need more help feel free to comment in here.

**Closed by michael-grunder** 2019-07-19 16:32 UTC
