### ISSUE TITLE
Couldn't map cluster keyspace using any provided seed

### ISSUE THREAD

**Issue by fidelhuang** [phpredis/phpredis#1532] opened 2019-03-27 15:18 UTC
### I'm seeing this behaviour on
- OS: centos7
- Redis:4.0.12
- PHP:5.4.6
- phpredis:4.30   pecl install redis

### Steps to reproduce, backtrace or example script
cluster work ok.
redis-trib.rb check 127.0.0.1:6380    is ok

$redis = new RedisCluster(NULL,Array('127.0.0.1:6380','127.0.0.1:6381'), 1.5, 1.5, true,'mypassword');
var_dump($obj_cluster);

Uncaught exception 'RedisClusterException' with message 'Couldn't map cluster keyspace using any provided seed

**Comment by michael-grunder** [comment] 2019-03-27 15:30
Does using `redis-cli -c -p 6380` work as expected (e.g. getting and setting keys is fine?)

**Comment by Thomas-1985** [comment] 2019-03-27 21:54
Hi
My bug was closed as a duplicate of this one.
In my case i can connect to the redis cluster with redis-cli, so the cluster seems to work.

**Comment by fidelhuang** [comment] 2019-03-28 01:58
@michael-grunder  redis-cli -c -p 6380 work is ok

**Comment by michael-grunder** [comment] 2019-03-28 02:14
Hi,

Are you sure that you are passing the correct password?  Another thing you can try is to create a non cluster connection and make sure you are able to communicate with a specific node via a `Redis` object.

**Comment by husnurrsyafni** [comment] 2019-04-02 05:35
Hi,
I've run into similar problem here. I have a redis cluster that has been set up in kubernetes. I created a NodePort for accessing the cluster. redis-cli -c works perfectly. I tried connecting my application to the redis cluster so that my application can use the redis cluster for storing user session data. It's unsuccessful and return the same error as the issue above had.

php version is 5.6.40
php-redis version 4.2.0

thanks.

**Comment by skjnldsv** [comment] 2021-07-21 09:28
~~Anyone found a fix?~~

~~php 8.0.8~~
~~php-redis 5.3.4~~

EDIT: realized I was misusing the php call...

```php 
#Fails 
new \RedisCluster(null, $config['seeds'], $timeout, $readTimeout, $auth, $connectionParameters);
#Works
new \RedisCluster(null, $config['seeds'], $timeout, $readTimeout, false, $auth, $connectionParameters);
```

**Comment by michael-grunder** [comment] 2022-10-06 02:13
Going to close this old issue, but if anyone is still having trouble I am happy to try and help.

**Closed by michael-grunder** 2022-10-06 02:13 UTC
