### ISSUE TITLE
Return type incorrect if Redis fails

### ISSUE THREAD

**Issue by kkmuffme** [phpredis/phpredis#1921] opened 2021-02-02 14:11 UTC
e.g. zRange, mGet,... have param @return array

e.g.

``` 
$redis->zRange( $queue, 0, -1, true );
```

However they do not return array in all cases. e.g. if redis has some internal issues (e.g. LOADING redis into memory, ...) these functions do not return an array.
Please fix the @return type so it also correctly shows this

**Comment by yatsukhnenko** [comment] 2021-03-01 20:10
@kkmuffme phpredis returns `false` in case of failure. This is by design. Did you mean that this behaviour isn't described in docs for `zRange` command?

**Comment by kkmuffme** [comment] 2021-03-02 06:55
>Did you mean that this behaviour isn't described in docs for zRange command?

Yes

**Comment by kkmuffme** [comment] 2021-11-17 08:44
@yatsukhnenko fyi this is becoming a problem, since static analysis tools (psalm, phpstan) flag errors if we check for a false value, which is not declared in the @return type.

e.g. `->mget( array( 'hello', 'world' ) )` with redis being offline (or other error), it returns `false` even though phpdoc is `@return array`

Psalm will flag as `RedundantCondition` then

**Comment by kkmuffme** [comment] 2021-12-09 23:30
Same also reported here https://github.com/phpredis/phpredis/issues/1923

**Comment by kkmuffme** [comment] 2021-12-09 23:31
Could this please get fixed? psalm/phpstan are reporting errors basically everywhere, since the docs and stubs are incorrect.

**Comment by halnique** [comment] 2022-07-08 10:33
Any progress on this issue?
There is a similar problem with `zRank/zRevRank`.
I am having trouble with phpstan because I get warnings....

If zRank/zRevRank commands executed on a key or member that does not exist, it cannot to return value as an int.
(Because rank cannot define it.)
It must return false (or something indicating that it does not exist).

**Comment by michael-grunder** [comment] 2022-10-13 03:23
Closing this issue since #2015 was merged.

**Closed as completed by michael-grunder** 2022-10-13 03:23 UTC
Labels: documentation problem, not a bug
