### ISSUE TITLE
Redis pipeline memory leak?

### ISSUE THREAD

**Issue by TrystanLea** [phpredis/phpredis#2376] opened 2023-09-04 16:27 UTC
Hello, Im using the following code to load in input data in our application (https://github.com/emoncms/emoncms/)

        $pipe = $this->redis->multi(Redis::PIPELINE);
        foreach ($inputids as $id) {
            $pipe->hGetAll("input:$id");
        }
        $result = $pipe->exec();

This seems to give me a memory leak with the latest version of phpredis develop branch and php 8.1.23 (raspberrypi os 32-bit, may 3rd debian 11 bullseye, kernel 6.1.21-v8+. 

The issue remains with hMGet but is not present with hGet with a single key.

This has been working fine for years without the memory issue and seems to have only become apparent this year, first reported issue around April 2023

Let me know if there is any other information that I can provide to assist in any way.

**Comment by mfn** [comment] 2023-09-19 16:00
(Tried to) upgrade to Redis 6 today and confirm, the pipeline feature leaks memory.

This short script was enough to trigger the linux OOM:
```php
<?php

$redis = new Redis();
$redis->connect('redis');

while (true) {
    $redis->pipeline();
    $redis->exec();
}
```
=> with 6.0.0 it's killed after a minute or so (depending on the RAM of the [virtual] machine, so be careful)
  ```
  root@e0acc6751f6c:/prject# php test_redis.php
  Killed
  ```
=> with 5.3.7 no problems, runs and runs

**Comment by mfn** [comment] 2023-09-19 22:26
Using `git bisect` I found this being the breaking commit 5a643b62d2177a009ab595ac987c97443eda44d5 , which is part of https://github.com/phpredis/phpredis/pull/2326 .

Whilst doing this I also found https://github.com/phpredis/phpredis/issues/2390 , it was actually part of the same commit which introduced the leak.

**Comment by yatsukhnenko** [comment] 2023-09-23 11:14
@TrystanLea @mfn issue should be fixed in `develop` branch, could you test it?

**Comment by mfn** [comment] 2023-09-24 10:09
@yatsukhnenko with my test script I can confirm I can't reproduce the memory leak nor the crash!

**edit:** I tested with `6.0.1` installed via pecl, since I saw it was already taggad. Not sure if there's a way to test the main/master/develop branch diretly via pecl? But I figure that it's good enough 🤞🏼

**Closed as completed** 2023-09-24 13:17 UTC

**Comment by TrystanLea** [comment] 2023-11-16 17:03
All working fine for me now, thanks a lot for fixing this!
