### ISSUE TITLE
zAdd NX option

### ISSUE THREAD

**Issue by diegotez** [phpredis/phpredis#760] opened 2016-03-14 15:35 UTC
Hello,
I'm was searching and seems NX option is not yet supported for zAdd command.
Are you planning to add it in near future?
Thanks in advance!

**Comment by michael-grunder** [comment] 2016-03-15 17:40
Hey,

Looks like this is a new feature since 3.0.2.  It's not difficult to add so I might be able to include it before we cut a new PECL release.

**Comment by diegotez** [comment] 2016-03-15 17:46
Thanks a lot!! ;)

**Comment by iprok** [comment] 2016-11-24 19:26
Hello! Is the feature still planned? Will be great to see it in some version supporting PHP 5.6. phpredis seems to be the fastest version for now.

**Comment by yatsukhnenko** [comment] 2016-11-28 12:37
@michael-grunder, I'm going to process NX|XX, CH and INCR options as an array just like you did for `set` command but here it may optionally appear after first argument. Something like this:
```
$redis->zAdd('key', array('XX'), 'score0', 'member0', 'score1', 'member1', 'score2', 'member2');
```
What do you think?

**Comment by michael-grunder** [comment] 2016-11-30 20:52
Hey,

That seems like a good solution to me.  It should work just fine even with serialization enabled, as without an option array the second argument would be a score (which we wouldn't serialize anyway).

The only other option would be to create something like `zAddEx` but I think your solution is better.

:smiley:

**Comment by yatsukhnenko** [comment] 2016-11-30 21:40
Thanks, Michael :) merged #1035

**Closed by yatsukhnenko** 2016-11-30 21:40 UTC

**Comment by bacheson** [comment] 2018-05-22 20:37
I can't for the life of me get this to work and it's not in the documentation...is there somewhere that explicitly illustrates how this works?

**Comment by michael-grunder** [comment] 2018-05-22 20:46
Hey,

What are you having trouble with?  Here is an example call using the `NX` option:

```php
$obj_redis = new Redis();
$obj_redis->connect('127.0.0.1', 6379);
$obj_redis->zAdd('myset', ['NX'], 1.0, 'member', 1.5, 'member2');
```

I see that reflected in redis-cli:
```bash
1527021902.935047 [0 127.0.0.1:35116] "ZADD" "myset" "NX" "1" "member" "1.5" "member2"
```

You might want to make sure you're running a new enough version of Redis that supports the options by trying the command manually in redis-cli.

**Comment by bacheson** [comment] 2018-05-22 20:54
I'm running Redis 4.0.9. The following command does not work:
`$redis->zAdd('queue', ['NX'], 1.5, $job)`

Oddly this does work but doesn't allow me to set a score:
`$redis->zAdd('queue', ['NX'], $job)`

**Comment by bacheson** [comment] 2018-05-22 22:28
Nevermind ... this was caused by an underlying container running an old version of php-redis ... sorry for bothering you...thanks so much for such a quick, helpful response

**Comment by michael-grunder** [comment] 2018-05-22 22:29
Perhaps you are running a version of phpredis that does not have this feature?

**Comment by bacheson** [comment] 2018-05-22 22:36
I posted my response at the exact same time....yup that was it

**Comment by lovelock** [comment] 2019-04-11 08:24
https://github.com/JetBrains/phpstorm-stubs
the stubs do not contain the update, let me do the last.
