### ISSUE TITLE
Possible to bypass auto serialize/unserialize or specify serializer?

### ISSUE THREAD

**Issue by giantninja** [phpredis/phpredis#1473] opened 2018-12-05 21:45 UTC
Apologies if this is the wrong place for this, but I've been using igbinary as the serializer via:
```
$client->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
```
which works as intended, however in addition to normal php caching of DB query results and that sort of data, I'm also storing session data as hash maps in redis, which is also used by a Java service we built, and there doesn't seem to be any igbinary support for deserializing in Java.

Is there a way to bypass on a per method basis (i.e. `hMSet()`) the auto serialization of values, or a way to manually specify the serializer when setting the value (in my case, specify `Redis::SERIALIZER_NONE`) ?

The auto serializing/unserializing works great, but since I'd like to avoid creating a separate `Redis()` object just for the session handling, it'd be great to specify or bypass the serializer set via `setOption` on the Redis object instance.  Is that something that can be done or is handling the serializing steps manually the only way? (aside from having a second Redis client object configured without the serializer?

**Comment by yatsukhnenko** [comment] 2019-12-08 19:10
@giantninja sorry for the delay 😅 `setOption` is still the only way to disable serialisation from PHP code and yes it should be called manually

**Comment by michael-grunder** [comment] 2020-03-02 19:55
Closing this issue since it's not a bug in phpredis.

**Closed by michael-grunder** 2020-03-02 19:55 UTC
