### ISSUE TITLE
ipv6 issue with RedisCluster

### ISSUE THREAD

**Issue by Palethorn** [phpredis/phpredis#750] opened 2016-02-09 13:47 UTC
It seems like the RedisCluster doesn't support ipv6:
`
PHP Warning:  RedisCluster::set(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /root/redis.php on line 4
PHP Warning:  RedisCluster::set(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /root/redis.php on line 4
PHP Warning:  RedisCluster::set(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /root/redis.php on line 4
PHP Fatal error:  Uncaught exception 'RedisClusterException' with message 'Can't communicate with any node in the cluster' in /root/redis.php:4
Stack trace:
#0 /root/redis.php(4): RedisCluster->set('test', 1)
#1 {main}
  thrown in /root/redis.php on line 4
`
I haven't tested using single node but I'm assuming the same problem.

**Comment by michael-grunder** [comment] 2016-02-09 16:57
Interesting.  The connection code just wraps php streams, so it's possible that this isn't too hard to solve.  I'll take a look.

**Comment by michael-grunder** [comment] 2016-02-09 20:33
This actually looks like it's just a matter of detecting ipv6 and passing in the correct `[host]:port` format to the PHP stream API.  I should be able to get this resolved without too much trouble.

**Comment by Palethorn** [comment] 2016-02-10 08:06
I presumed as much since the redis-cli implementation had the same problem.

**Comment by michael-grunder** [comment] 2016-02-13 02:22
Hey,

I've pushed the branches `develop-ipv6` and `php7-ipv6` that support IPv6 style addresses.  All of the unit tests are passing for me on both branches but I would still like to do some more testing and if you don't mind testing on your end that would be great.

Cheers!
Mike

**Comment by Jerry-Shaw** [comment] 2016-02-13 07:52
@michael-grunder , is there any other changes between normal branch and ipv6 branch? Or, we can also use ipv6 branch on ipv4 network system?

**Comment by michael-grunder** [comment] 2016-02-13 17:36
Yes everything should work for both ipv4 and ipv6.  I just used separate branches until I get feedback that there aren't any regressions.  If there aren't any these changes will be merged back into develop and php7

**Comment by Palethorn** [comment] 2016-02-15 10:53
I'll test this today and let you know.

**Comment by Jerry-Shaw** [comment] 2016-02-15 11:27
Good work.

**Comment by Palethorn** [comment] 2016-02-15 14:15
I've tested basic functionality and it works now.

**Comment by michael-grunder** [comment] 2016-02-15 16:50
Awesome, let me know if you encounter any issues :)

**Closed by michael-grunder** 2016-02-15 16:50 UTC
