### ISSUE TITLE
Error: Undefined index: host

### ISSUE THREAD

**Issue by DSGM22** [phpredis/phpredis#2243] opened 2022-11-07 09:11 UTC
### Expected behaviour
Trying to switch to Phpredis from Predis successfully
### Actual behaviour
Switch to Phpredis from Predis unsuccessful
### I'm seeing this behaviour on
- OS: Linux Mint 20.3 (Una)
- Redis: 7.0.4
- PHP: 7.4.3
- phpredis: 5.1.1

### Steps to reproduce, backtrace or example script
Since I wasnt able to use Redis::keys, Redis::scan,and any other functions except Redis::get and Redis::set while using Predis(Error: Cannot use 'KEYS' with redis-cluster), I decided to switch to Phpredis. I was able to setup and use it successfully with a newly setup Laravel 6.20 project but it throws the above mentioned issue while integrating it with an already exisiting Laravel 6.20 project which was functioning on Predis till now.

On reverse engineering, found that **../vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php** file accesses host in **protected function formatHost** as **$options['host'] instead of $options[0]['host']**. But since changes cant be made to vendor files, can anyone help with a proper solution to successfully switch from Predis to Phpredis?

### I've checked
- [ ] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment] 2022-11-12 21:22
This isn't a bug in PhpRedis, but rather an issue interacting with Laravel.

You might need to reconfigure your setup, but I honestly don't know anything about Laravel so can't really be of any assistance.

**Comment by michael-grunder** [comment] 2022-11-16 18:47
Going to close this since it's not a bug with PhpRedis but an issue with how the framework and PhpRedis interact.

**Closed as completed by michael-grunder** 2022-11-16 18:47 UTC
