### ISSUE TITLE
smembers intermittent protocol error, got '#012' as reply type byte

### ISSUE THREAD

**Issue by tomponline** [phpredis/phpredis#1389] opened 2018-08-23 09:59 UTC
### Expected behaviour

smembers runs without error.

### Actual behaviour

Since upgrading from phpredis 2.2.3 to 4.1.1 we are experiencing intermittent protocol errors.
Nothing else has changed except the version of phpredis.
Intermittently the call to smembers triggers an error `protocol error, got '#012' as reply type byte`

Example code that triggers error intermittently:

```
$cacheDb->smembers($workingSetKey);
```

### I'm seeing this behaviour on
- OS: CentOS 6 x86_64
- Redis: 3.2.0 (32bit)
- PHP: 5.5.38 (64bit)
- phpredis: 4.1.1

### Steps to reproduce, backtrace or example script

Not been able to identify it yet, doesn't happen on all smembers calls, so it seems to be a certain combination of previous commands on the connection that causes this.

### I've checked
- [x] There is no similar issue from other users
- [ ] Issue isn't fixed in `develop` branch

**Comment by tomponline** [comment] 2018-08-23 10:00
I've looked at some other similar issues, but nothing that matches exactly, and they were marked as resolved in earlier versions, however we are still seeing it.

**Comment by 719media** [comment] 2019-04-24 00:07
I'm sorry I can't help reproduce, but I get this on redis 5.0.3 (aws redis) and latest phpredis. I'm using php 7.1.28. The error seems to be related to the use of persistent connections, as I've never seen it when I'm not using persistent connections. However, I cannot reliably reproduce.

**Comment by yatsukhnenko** [comment] 2019-04-24 04:28
@719media do you use persistent connection with pooling enabled?

**Comment by 719media** [comment] 2019-04-24 07:32
I'm sorry I was incorrect, I was using phpredis 4.2.0 driver, and just now updated to the 4.3.0 version tonight and will let you know of any changes. I am using the default install from pecl,  so I don't believe that `pooling_enabled` is set to 1, as I have not specifically changed this setting, but am unclear on the documentation.

**Comment by 719media** [comment] 2019-04-24 16:10
Since upgrading to 4.3.0, the problem has subsided. I am continuing to use pconnect with redis.pconnect.pooling_enabled => 0 => 0 without issue

**Comment by yatsukhnenko** [comment] 2019-04-24 18:26
It's strange because pconnect works the same in 4.2.0 and 4.3.0 when pooling is disabled

**Comment by michael-grunder** [comment] 2019-06-02 20:40
Closing this issue since it seems to have magically fixed itself.  Please reopen if it's not actually resolved.

**Closed by michael-grunder** 2019-06-02 20:40 UTC
