### ISSUE TITLE
"NOAUTH Authentication required" error thrown when authentication is provided

### ISSUE THREAD

**Issue by JimmyBanks** [phpredis/phpredis#1816] opened 2020-07-23 14:17 UTC
### Expected behaviour
When authentication is provided (and correct), a NOAUTH Authentication required error should not be thrown

### Actual behaviour
On random intervals (for our web app, this issue occured on July 14, and then recurred again on July 23, with the issue continuing to occur so far for over 13 hours)

### I'm seeing this behaviour on
- OS: Ubuntu 18.04.4
- Redis: 4.0.14
- PHP: 7.4.8
- phpredis: 5.3.1 (Persistent connections)

### Steps to reproduce, backtrace or example script
I am trying to determine how to reproduce this issue, I haven't yet been able to identify the cause.
I did notice that the issue was identified by Laravel previously: https://github.com/laravel/horizon/issues/744; however, it appears the issue was resolved. I am wondering if 5.3.1 re-introduced the issue, as for in our case the issue only started after 5.3.1 was released.

### I've checked
- [x] There is no similar issue from other users
- [x] Issue isn't fixed in `develop` branch

**Comment by michael-grunder** [comment] 2020-07-23 17:17
Potentially related to or a duplicate of #1757

I've got a hunch about what might be happening and will update this thread as well if I track it down.

**Comment by michael-grunder** [comment] 2020-07-23 19:34
I'm going to close this issue in favor of #1757 so it's all in one place.  Feel free to comment over there

**Closed as completed by michael-grunder** 2020-07-23 19:34 UTC
