### ISSUE TITLE
pcntl_fork causing “errno=32 Broken pipe”

### ISSUE THREAD

**Issue by penfold45** [phpredis/phpredis#474] opened 2014-05-17 17:57 UTC
Hi 

I am having issues with PHP notices after upgrading from php 5.4.26 to 5.4.28. I original thought it was a php issue but it may be related to this Redis extension.

The full details can be found here http://stackoverflow.com/questions/23713480/after-php-upgrade-pcntl-fork-causing-errno-32-broken-pipe

But basically when I am forking, whenever a child closes, except for the first child, I get an error saying: 

```
Notice: Unknown: send of 6 bytes failed with errno=32 Broken pipe in Unknown on line 0
```

It feels like the first child is closing the connection to Redis and then the following children try and close the same connection.

It appears that this has only just started being an issue since either PHP 5.4.27 or 5.4.28

Could this be a phpredis issue?

I have Redis Version => 2.2.5 installed

**Comment by jat001** [comment] 2015-01-12 09:22
I know how to fix this bug. Just close the connect to redis before pcntl_fork and re-connect to redis after pcntl_fork.
example: https://github.com/jat001/auto-upgrade-scripts/blob/master/server/lib/db.php#L68

**Comment by anton000** [comment] 2015-01-21 19:37
no updates?

**Comment by roeyb** [comment] 2015-02-03 12:31
+1

**Comment by diandianxiyu** [comment] 2015-02-11 08:30
+1

**Comment by rlweb** [comment] 2015-02-20 09:39
+1

**Comment by schlaus** [comment] 2015-03-20 12:12
+1

**Comment by lexvjatkin** [comment] 2015-03-26 18:33
Same here. PHP 5.5.9, phpredis 2.2.7

Simple script to replicate this bug https://gist.github.com/lexvjatkin/8897f1be48b9e8747b7d#file-redis-pipe-bug-php

Expected result:

    bool(true)

Actual result:

    bool(true)
    PHP Notice:  Unknown: send of 6 bytes failed with errno=32 Broken pipe in Unknown on line 0
    
    Notice: Unknown: send of 6 bytes failed with errno=32 Broken pipe in Unknown on line 0
    
    PHP Notice:  Unknown: send of 6 bytes failed with errno=32 Broken pipe in Unknown on line 0
    
    Notice: Unknown: send of 6 bytes failed with errno=32 Broken pipe in Unknown on line 0

Connections before script (`lsof -i :6379`):

    COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
    redis-ser 20319 root    4u  IPv4 10422993      0t0  TCP *:6379 (LISTEN)

Connections after first child forked:

    COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
    redis-ser 20319 root    4u  IPv4 10422993      0t0  TCP *:6379 (LISTEN)
    redis-ser 20319 root    6u  IPv4 10446216      0t0  TCP config0.local:6379->config0.local:52050 (ESTABLISHED)
    php       21993  lex    8u  IPv4 10446860      0t0  TCP config0.local:52050->config0.local:6379 (ESTABLISHED)
    php       21994  lex    8u  IPv4 10446860      0t0  TCP config0.local:52050->config0.local:6379 (ESTABLISHED)

Connections after second child forked:

    COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
    redis-ser 20319 root    4u  IPv4 10422993      0t0  TCP *:6379 (LISTEN)
    php       21993  lex    8u  IPv4 10446860      0t0  TCP config0.local:52050->config0.local:6379 (CLOSE_WAIT)
    php       22020  lex    8u  IPv4 10446860      0t0  TCP config0.local:52050->config0.local:6379 (CLOSE_WAIT)

Connections after third child forked:

    COMMAND     PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
    redis-ser 20319 root    4u  IPv4 10422993      0t0  TCP *:6379 (LISTEN)

**Comment by lexvjatkin** [comment] 2015-03-26 19:06
Modified my gist a bit to see which process produces notice https://gist.github.com/lexvjatkin/8897f1be48b9e8747b7d/d46ccd5c2ffabb1c3a09118db80654cb382c6c96
and it's interesting -  third child at the end and following childs and then parent at the end.

My log:

    bool(true)
    Parent pid: 22968
    Child pid: 22969
    Child pid: 22971
    Child pid: 22972
    Error in PID 22972: Unknown: send of 6 bytes failed with errno=32 Broken pipe
    Child pid: 22973
    Error in PID 22973: Unknown: send of 6 bytes failed with errno=32 Broken pipe
    Child pid: 22974
    Error in PID 22974: Unknown: send of 6 bytes failed with errno=32 Broken pipe
    Error in PID 22968: Unknown: send of 6 bytes failed with errno=32 Broken pipe

**Comment by sanvibyfish** [comment] 2015-05-29 08:58
I have same problem, I use pconnect to connect redis. 

After fork, I pconnect again, But nothing help.

Sometime always throw exception like this.

```
Exception Redis::lLen(): send of 38 bytes failed with errno=32 Broken pipe in
```

This code just manager jobs, and run it.

```
        $files = glob(__DIR__ . '/jobs/*.php');
        foreach ($files as $_file) {
          $this->workers[$name . $i] = pcntl_fork();
          $redis = new Redis();
          $redis->pconnect('127.0.0.1', 0.3);
          if ($this->workers[$name . $i] === 0) {
            posix_kill(posix_getpid(), SIGTERM);
          }
        }
        while (count($this->workers)) {
            $pid = pcntl_wait($status);
            usleep(50000);
        }

```

Then the unix crontab will run it. Same job will pconnect Redis, after  pcntl_fork() pconnect Redis can't fix

**Comment by xuecai** [comment] 2015-09-09 14:39
use pcntl_fork causing "errno=32 Broken pipe" 
phpredis 2.2.7

**Comment by lixiphp** [comment] 2015-10-19 08:12
+1

**Comment by driq** [comment] 2015-11-02 09:02
Having the same issue when using kriswallsmith/spork

**Comment by lixiphp** [comment] 2015-11-03 06:44
this bug is from php pcntl, just in the worker colse redis, will solve this problem.

**Comment by giraclion** [comment] 2016-02-03 00:40
Same issue happens when using PHP 5.5.9 + phpredis 2.2.7 + redis engine 2.8.19 + Magento CE 1.9.0.1 + [Cm_Cache_Backend_Redis](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis) environment. 
Error:
```
Redis::exec(): send of 8192 bytes failed with errno=32 Broken pipe
```

**Comment by jaymecd** [comment] 2016-03-14 20:37
+1

**Comment by sierrajb** [comment] 2016-03-15 19:52
+1

**Comment by piotrkochan** [comment] 2016-04-05 12:03
+1

**Comment by jimyaghi** [comment] 2016-06-08 08:09
+1

**Comment by sapzxc** [comment] 2016-07-09 08:17
+1 :)

**Comment by vanquang9387** [comment] 2016-08-02 02:02
+1

**Comment by consatan** [comment] 2016-08-31 09:36
+1

**Comment by leepin** [comment] 2016-09-19 05:55
+1

**Comment by robbieaverill** [comment] 2016-10-06 19:49
You guys know there's now a "+1" equivalent "like button" on GitHub right, without spamming the participants with emails (unless that's your objective!)

**Comment by j-d** [comment] 2016-11-02 17:56
+1

**Comment by taskinosman** [comment] 2016-11-18 13:24
php 5.5.9 suddenly started doing same behaviour. I cannot use it anymore in production. This is high priority bug

**Comment by yatsukhnenko** [comment] 2016-11-18 15:24
Could someone provide script which cause this error?

**Comment by lexaurin** [comment] 2016-11-23 07:37
@yatsukhnenko  here you go https://gist.github.com/lexaurin/8897f1be48b9e8747b7d/d46ccd5c2ffabb1c3a09118db80654cb382c6c96

**Comment by yatsukhnenko** [comment] 2016-11-23 07:49
@lexaurin, thanks.
There is no error on my gentoo box
```
php redis-pipe-bug.php 
bool(true)
Parent pid: 27921
Child pid: 27922
Child pid: 27923
Child pid: 27924
Child pid: 27925
Child pid: 27926
```
Tested on php5.3-php7.1

**Comment by yatsukhnenko** [comment] 2016-11-23 07:51
@lexaurin depends environment?

**Comment by lexaurin** [comment] 2016-11-23 08:15
I can't reproduce it on my desktop too (PHP 7.0.8-0ubuntu0.16.04.3) 

Problem was on Debian machine a while ago and I don't have access there anymore. PHP 5.5.9, phpredis 2.2.7 at that time.

Maybe someone with "+1" can provide more infomration and test it out.

**Comment by yatsukhnenko** [comment] 2016-11-23 08:54
phpredis 2.2.7 is to old. problem may be fixed long time ago :)

**Comment by lexaurin** [comment] 2016-11-23 09:13
I know, it was reported in 2014. If no one can confirm it on newer versions of phpredis I suggest to close this bug with resolution "Upgrade to 3.x"

**Comment by ppanphper** [comment] 2017-01-04 03:25
PHP7.1.0+phpredis-3.1.0
[2017-01-04 03:18:24.999684] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:24.999892] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:24.999925] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.158000] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.220300] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.223600] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.224560] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.224870] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.226500] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.227390] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.228110] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.229100] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.230710] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.230970] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.231740] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]
[2017-01-04 03:18:25.233500] [Notice] RedisCluster::set(): send of 3182 bytes failed with errno=32 Broken pipe at /home/development/pandy/Swoole_Pool/RedisPool/RedisClient.php[512]

**Comment by zoglun** [comment] 2017-03-23 14:57
Same error happen to me under debian8, **redis 3.2.7,** with php7.0 & Mediawiki 1.28.
PHP Notice:  Redis::set(): send of 82 bytes failed with errno=32 Broken pipe in /wiki/includes/libs/redis/RedisConnRef.php on line 96

**Comment by ngoctruongbc** [comment] 2017-03-28 04:41
Same error happens to me under CentOS 6 , Redis 3.2.1 with PHP 7.0 & Magento 2
```
[2017-03-25 00:00:38] Subscription Logger Publish profile to message queue.CRITICAL: ErrorException: Redis::hGet(): send of 71 bytes failed with errno=32 Broken pipe in /opt/nestle/magento/releases/20170324062419/vendor/colinmollenhour/credis/Client.php:1044
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(8, 'Redis::hGet(): ...', '/opt/nestle/mag...', 1044, Array)
#1 /opt/nestle/magento/releases/20170324062419/vendor/colinmollenhour/credis/Client.php(1044): Redis->hGet('zc:k:b22_GLOBAL...', 'd')
#2 /opt/nestle/magento/releases/20170324062419/lib/internal/Cm/Cache/Backend/Redis.php(211): Credis_Client->__call('hget', Array)
#3 /opt/nestle/magento/releases/20170324062419/vendor/magento/zendframework1/library/Zend/Cache/Core.php(306): Cm_Cache_Backend_Redis->load('b22_GLOBAL_PRIM...', false)
```

**Comment by yatsukhnenko** [comment] 2017-03-28 04:46
@ppanphper, @zoglun, @ngoctruongbc, do you have a script to reproduce this issue?

**Comment by virgofx** [comment] 2017-03-28 13:38
In my opinion this should be closed as it's a duplicate of #70 

@yatsukhnenko Script to reproduce is here: https://github.com/phpredis/phpredis/issues/70#issuecomment-151607739

**Comment by yatsukhnenko** [comment] 2017-03-28 15:02
Duplicate #70

**Closed by yatsukhnenko** 2017-03-28 15:02 UTC

**Comment by weixuan19930** [comment] 2018-09-18 03:52
Same error happens in swoole worker...
